---
apiVersion: v1
kind: Secret
metadata:
  name: bareos-secret
  namespace: bareos
type: Opaque
stringData:
  db_password: "testpassword"
  db_admin_user: "postgres"
  db_admin_password: "testpassword"
  bareos_sd_password: "testpassword"
  bareos_fd_password: "testpassword"
  bareos_webui_password: "testpassword"
  admin_mail: "admin@test.com"
  webhook_url: "http://test.com"
