---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-ingress
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/haproxy-ingress/manifests
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: haproxy-ingress
      namespace: haproxy-ingress
  patches:
    - target:
        kind: HelmRelease
        name: haproxy-ingress
      patch: |
        - op: replace
          path: /spec/values/controller/replicaCount
          value: 1
        - op: replace
          path: /spec/values/defaultBackend/replicaCount
          value: 1
