---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    engines:
      replicated:
        mayastor:
          enabled: false
      local:
        zfs:
          enabled: false
        lvm:
          enabled: false
    zfs-localpv:
      crds:
        zfsLocalPv:
          enabled: false
    lvm-localpv:
      crds:
        lvmLocalPv:
          enabled: false
