#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: openebs-triple-replica
#parameters:
#  protocol: nvmf
#  repl: "3"
#provisioner: io.openebs.csi-mayastor
#reclaimPolicy: Retain
#volumeBindingMode: Immediate
#allowVolumeExpansion: true
