---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud-fastnetserv
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: nextcloud
      version: ">=3.1.2"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      tag: stable-apache
      pullPolicy: Always
    podAnnotations:
      backup.velero.io/backup-volumes: nextcloud-main
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/client-max-body-size: 0
        nginx.ingress.kubernetes.io/proxy-body-size: 0
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      tls:
        - secretName: nx-fastnet-tls
          hosts:
            - nx.fastnetserv.cloud
    nextcloud:
      host: nx.fastnetserv.cloud
      ## Use an existing secret
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
      configs:
        reverse-proxy.config.php: |-
          <?php
          $overwriteHost = getenv('OVERWRITEHOST');
          if ($overwriteHost) {
            $CONFIG['overwritehost'] = $overwriteHost;
          }

          $overwriteProtocol = getenv('OVERWRITEPROTOCOL');
          if ($overwriteProtocol) {
            $CONFIG['overwriteprotocol'] = $overwriteProtocol;
          }

          $overwriteCliUrl = getenv('OVERWRITECLIURL');
          if ($overwriteCliUrl) {
            $CONFIG['overwrite.cli.url'] = $overwriteCliUrl;
          }

          $overwriteWebRoot = getenv('OVERWRITEWEBROOT');
          if ($overwriteWebRoot) {
            $CONFIG['overwritewebroot'] = $overwriteWebRoot;
          }

          $overwriteCondAddr = getenv('OVERWRITECONDADDR');
          if ($overwriteCondAddr) {
            $CONFIG['overwritecondaddr'] = $overwriteCondAddr;
          }

          $trustedProxies = getenv('TRUSTED_PROXIES');
          if ($trustedProxies) {
            $CONFIG['trusted_proxies'] = array_filter(array_map('trim', explode(' ', $trustedProxies)));
          }
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'trusted_proxies'   => ['10.10.8.20'],
            'default_phone_region' => 'IT',
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 800m
        # note that Kubernetes currently requires cpu or memory requests and limits before hugepages are allowed.
        memory: 4096Mi
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      ## Use a existing secret
      existingSecret:
        enabled: true
        secretName: nextcloud-db-secret
        usernameKey: db-username
        passwordKey: db-password
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
      auth:
        existingSecret: nextcloud-mariadb
        database: nextcloud
        username: nextcloud
    redis:
      enabled: true
      master:
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
      replica:
        replicaCount: 1
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
    persistence:
      enabled: true
      size: 100Gi
    metrics:
      enabled: false
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9205"
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
