apiVersion: v1
kind: Secret
metadata:
    name: onepassword-secret
    namespace: 1password
stringData:
    token: ENC[AES256_GCM,data:bDKYQQZ6v9tOo4PUbFjasHzK/GY4YpI7pFbIBW4nyFM9bhOMsBpHQLMUXEkn60X8Oi66rRBEQk6O5urL/jf1YOlIdqI6+LH/bf3tBs5ooIEQxoaraOLwwVCrsWECf2bimHUogyMSJ8JmdGFRtjbQqvY95WSVZyPt1gUdRkFo++y7Zf0Fjm3TIbia94K799iKHR78Ye3u2YNGe8891WvaXoperove+oTkZeHIX80pYcVv2gprDyCTddtkHDd7lc3aY0R6rvyA4rP0Xhpp5l6yxywThyk40ln/KEKTQp0zBU0HjCE4uT6Rac3JSHfWYkneE1Y8x2STSNrmYeO0vzGa5h84f2Racsg7lhTISFwTcGtw5AvfcwYdZ5yDh5xhhw4lICgJRAlMyfbUQ82Q3XuEguczu8V2Aa/1oR+WIQs21pKst+i+mAKBAAe8TvJn9uYgD6T3jUMDR/d0O1ecAb/6XARzGGY7Ktrw7vXDQ56PtRgWDfYS/lXJhwrRd/lCJpy+BnreMPOGjWY948Z2lb8oDDKFZCB7RSygiyU/znQQE0k2GzZKUxak7URO1a1VpocDmX7iZ8sU6wrBk6HOEKq7uB/1UI0bdIstrk1/FT4nJYraM/YX2XBzmW1u1DZnPJbLky+Dil764jYktzJcdrgiVXJuecR+xROQvczKWOqnF9MnE+C0NuPwAslthoKg9NtnObjN9BCRHHvfYGMIqckC3wXe9/xQW6hsxiY4fhWCTZrksZ2v2GRGzEVsgotJkacBwBYQRyj3ujHnFcMpZukr/E3zwY0CTyhk9FivDOchqZEWy0JHB7E3PP94TCX2pOKAGfnQsnxFfqLYFvH2tCZFGGAw,iv:2uKRwY+zlINJHi1KgWt9hvhpJW4Uasrrv61qA2SKjc8=,tag:+xEA1g2eLqcsFHUkLkUKbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlem1yNndxaWNreVBwTi9G
            SGdnb1cwQ3NnTHJJd1ppMVhTK2ZYczJtL0U4Cm53Mmt0WFZWanhuOVJBSy9hSjNU
            bFp3Vkw0UkdWZU0xdElRczNKNGJXTG8KLS0tIG9XcHJXaitKVXpjSmhldXB1RGdW
            aW9NZXVNcXU3YTNXaHA1WVBEOEkybWsK+E5iPXaew6ZUDNgN89Q5y50vnGhqBbdl
            O3/zEpseTGehmJCw1lDbnGaUBihAQkqNvIIB2wn2bK0WVXmrS/duLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1we4kjkxtqxd6ne9tx458tw2jsswwfzll8rs6mjsa4g40zn8nj97qk9mf46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T16:56:20Z"
    mac: ENC[AES256_GCM,data:DYca4PV64jCclLlxgIW1nZp7b9Vo1fkSQZZ43osroCwy2bk22FmTJAenlrN9k4pMc2G+KxVBTF7EI8SzOpNhbtWD6QhuCgn4L6wcWXvVFgqMtM0ubRYtDoEV2YNVpFFwbvZJH6mg3y2MTaKZuInSzV8SkLYTUGViMwRXgA36P3A=,iv:FRX/gsBYS+/0cuLUeymugpGMUFG4JokQn4R1uf68UxI=,tag:oRNLkCJGhwFTnywiX7Wfkw==,type:str]
    version: 3.13.3
