apiVersion: v1
kind: Secret
metadata:
    name: onepassword-secret
    namespace: 1password
stringData:
    token: ENC[AES256_GCM,data:cd3ylLr1Z8+GwLoNWtKZ7vjKeRCURi0H7+77iuxxUwcBp5XAXDxBErm0,iv:agulwxGccJe6LJn7S/Z7yMq4UE62vmZYODIboNswizI=,tag:JB5i/IBCduPDKeJ+n3SRvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTGFMdmNwTFNFSWNTTkEy
            NGpyc1h3Ui8xUTJQdnRMdDl6N0VOM3F3eno0CkYyV0E4aElBQzFPS1BtUVZtbVc5
            dSt4N2NQaS9hbzVYekJ4MFdnNktMS3cKLS0tIHRDd3JVYXVnVUZ5N0IzL2ZiTkE1
            cDdBUGtwcUp1VDRUQ0RQeitLZVljKzQKmI2lhE0kM/09n5rRlXKYdFinng68ALgp
            X8q/vWaCMZktu3ry3uk3tKKzwXX4iFF/V5qT8OzIxsb7ATDCqW9p8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1we4kjkxtqxd6ne9tx458tw2jsswwfzll8rs6mjsa4g40zn8nj97qk9mf46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T16:44:02Z"
    mac: ENC[AES256_GCM,data:TE8j2y8XFE68tIVrcW90gUz3u3G6/d0GuNBVXfpu6Fx14gsxgUX+MVRVpwDgLDkWrXMizenrYr9lezfWQIZrdiOd/hI1Sv6K3YLvakS1f69D7MSkqDWZmXakp77A8ElKSRqJV0SNJ9d0KZS2afgDx3n/Ck02+/O6/iCU2hXsGEo=,iv:Er86su7LlDlErosMiUvJPCmhwWE2YYgQM7bmQIaI7jw=,tag:SZGqJJvf0wlViGf9sCRA3g==,type:str]
    version: 3.13.3
