# Auto-generated resources for rabbit-01-psp
# Generated by proxmox-generate-tf.py
# Review and adjust as needed before applying

module "rabbit_satisfactory_shared_ddlns_net_lxc" {
  source = "github.com/dark-vex/terraform-proxmox-lxc?ref=49277d5e2d4eb8a5f3173e02965170aecde6711a" # v2.0.0
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = local.rabbit_secrets.lxc.satisfactory_shared_lxc
  vmid        = 806
  node_name   = "rabbit-01-psp"
  description = "Satisfactory shared Container"

  cpu_cores      = 4
  memory         = 12288
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd2"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_interfaces = {
    eth0 = {
      bridge       = "vmbr1"
      mac_address  = "BC:24:11:91:18:13"
      ipv4_address = "dhcp"
    }
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  manage_user_account = false

  tags = ["automation", "container", "lxc", "satisfactory", "ubuntu"]
}

module "rabbit_haproxy1_ddlns_net_lxc" {
  source = "github.com/dark-vex/terraform-proxmox-lxc?ref=49277d5e2d4eb8a5f3173e02965170aecde6711a" # v2.0.0
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = local.rabbit_secrets.lxc.haproxy1
  vmid        = 800
  node_name   = "rabbit-01-psp"
  description = "HAProxy Container for reverse proxy and load balancing"

  cpu_cores      = 4
  memory         = 2048
  swap           = 0
  disk_size      = 20
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_interfaces = {
    eth0 = {
      bridge       = "vmbr1"
      mac_address  = "BC:24:11:D1:06:0F"
      ipv4_address = "10.10.20.172/24"
      ipv4_gateway = "10.10.20.1"
    }
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  manage_user_account = false

  tags = ["automation", "container", "haproxy1", "lxc", "ubuntu"]
}

module "rabbit_test_mail_ddlns_net_lxc" {
  source = "github.com/dark-vex/terraform-proxmox-lxc?ref=49277d5e2d4eb8a5f3173e02965170aecde6711a" # v2.0.0
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = local.rabbit_secrets.lxc.test_mail
  vmid        = 804
  node_name   = "rabbit-01-psp"
  description = local.rabbit_secrets.lxc.test_mail
  console     = {}

  cpu_cores      = 2
  memory         = 2048
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "debian"

  network_interfaces = {
    eth0 = {
      bridge       = "vmbr1"
      mac_address  = "BC:24:11:F4:F9:86"
      ipv4_address = "10.10.20.103/24"
      ipv4_gateway = "10.10.20.1"
      ipv6_address = "dhcp"
    }
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = false

  manage_user_account = false

  tags = ["mail"]
}

module "rabbit_satisfactory_ddlns_net_lxc" {
  source = "github.com/dark-vex/terraform-proxmox-lxc?ref=49277d5e2d4eb8a5f3173e02965170aecde6711a" # v2.0.0
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = local.rabbit_secrets.lxc.satisfactory_lxc
  vmid        = 805
  node_name   = "rabbit-01-psp"
  description = "Satisfactory Container"

  cpu_cores      = 4
  memory         = 12288
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd2"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_interfaces = {
    eth0 = {
      bridge       = "vmbr1"
      mac_address  = "BC:24:11:56:15:A6"
      ipv4_address = "dhcp"
    }
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  manage_user_account = false

  tags = ["automation", "container", "lxc", "satisfactory", "ubuntu"]
}

module "rabbit_graylog_ddlns_net_lxc" {
  source = "github.com/dark-vex/terraform-proxmox-lxc?ref=49277d5e2d4eb8a5f3173e02965170aecde6711a" # v2.0.0
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = local.rabbit_secrets.lxc.graylog
  vmid        = 807
  node_name   = "rabbit-01-psp"
  description = local.rabbit_secrets.lxc.graylog

  cpu_cores      = 8
  cpu_limit      = 6
  memory         = 16384
  swap           = 4096
  disk_size      = 100
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_interfaces = {
    eth0 = {
      bridge       = "vmbr1"
      mac_address  = "BC:24:11:41:A8:4A"
      ipv4_address = "10.10.20.103/24"
      ipv4_gateway = "10.10.20.1"
    }
  }

  features = {
    nesting = true
  }

  console = {}

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = false

  manage_user_account = false

  tags = ["automation", "lxc"]
}

module "rabbit_pbs_01_psp_ddlns_net_lxc" {
  source = "github.com/dark-vex/terraform-proxmox-lxc?ref=49277d5e2d4eb8a5f3173e02965170aecde6711a" # v2.0.0
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = local.rabbit_secrets.lxc.pbs_01_psp
  vmid        = 802
  node_name   = "rabbit-01-psp"
  description = local.rabbit_secrets.lxc.pbs_01_psp

  cpu_cores      = 4
  memory         = 4096
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "debian"

  network_interfaces = {
    eth0 = {
      bridge       = "vmbr0"
      mac_address  = "BC:24:11:D1:13:50"
      firewall     = true
      ipv4_address = "192.168.122.101/24"
      ipv4_gateway = "192.168.122.1"
    }
  }

  console = {}

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  manage_user_account = false

  tags = ["backup"]
}

module "rabbit_squid_ddlns_net_lxc" {
  source = "github.com/dark-vex/terraform-proxmox-lxc?ref=49277d5e2d4eb8a5f3173e02965170aecde6711a" # v2.0.0
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = local.rabbit_secrets.lxc.squid_lxc
  vmid        = 801
  node_name   = "rabbit-01-psp"
  description = "Squid Proxy Container for content filtering"

  cpu_cores      = 2
  memory         = 2048
  swap           = 0
  disk_size      = 20
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_interfaces = {
    eth0 = {
      bridge       = "vmbr2"
      mac_address  = "BC:24:11:E3:04:A9"
      ipv4_address = "10.10.40.100/24"
      ipv4_gateway = "10.10.40.1"
    }
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  manage_user_account = false

  tags = ["automation", "container", "lxc", "proxy", "ubuntu"]
}

module "rabbit_rtmp1_ddlns_net_lxc" {
  source = "github.com/dark-vex/terraform-proxmox-lxc?ref=49277d5e2d4eb8a5f3173e02965170aecde6711a" # v2.0.0
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = local.rabbit_secrets.lxc.rtmp1_lxc
  vmid        = 803
  node_name   = "rabbit-01-psp"
  description = local.rabbit_secrets.lxc.rtmp1_lxc

  cpu_cores      = 8
  memory         = 8192
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd2"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_interfaces = {
    eth0 = {
      bridge       = "vmbr1"
      mac_address  = "62:F1:59:86:4E:CC"
      ipv4_address = "dhcp"
    }
  }

  console = {}

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  manage_user_account = false

  tags = ["automation", "lxc"]
}

# CODE-32: decommission mon-bgy (VM 808). Its description claimed
# "Proxmox monitoring - BGY site (pve-exporter + Grafana Alloy)", but live
# state (confirmed via the proxmox-rabbit MCP, read-only, before this
# change) showed no pve-exporter or teleport-client process running on it
# - only the pve-host-netmon Alloy config that was mistakenly deployed
# here instead of bare-metal rabbit-01-psp (see ansible/pve-host-netmon/).
# ansible/teleport-client and ansible/pve-monitoring's inventory entries
# for mon-bgy were declared intent that was apparently never actually
# applied to this host - nothing real is lost by removing it.
#
# Same removed{} pattern as CODE-29/CODE-30 (PR #2042, #2056): this
# module hardcodes lifecycle { prevent_destroy = true } internally with
# no override - `removed` bypasses it by design (the resource block is no
# longer declared) rather than overriding it. Live Proxmox state
# confirmed before this change: vmid 808, running, 512MB mem / 4GB disk /
# tags "automation;lxc;monitoring" all match this module's declaration,
# and list_ha_resources returned empty (nothing depends on it via HA).
removed {
  from = module.rabbit_mon_bgy_lxc.proxmox_virtual_environment_container.this

  lifecycle {
    destroy = true
  }
}
