# Auto-generated resources for rabbit-01-psp
# Generated by proxmox-generate-tf.py
# Review and adjust as needed before applying

module "rabbit_satisfactory_shared_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "satisfactory-shared.ddlns.net"
  vmid        = 806
  node_name   = "rabbit-01-psp"
  description = "Satisfactory shared Container"

  cpu_cores      = 4
  memory         = 12288
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd2"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:91:18:13"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  manage_user_account = false

  tags = ["automation", "container", "lxc", "satisfactory", "ubuntu"]
}

module "rabbit_haproxy1_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "haproxy1.ddlns.net"
  vmid        = 800
  node_name   = "rabbit-01-psp"
  description = "HAProxy Container for reverse proxy and load balancing"

  cpu_cores      = 4
  memory         = 2048
  swap           = 0
  disk_size      = 20
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:D1:06:0F"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "10.10.20.172/24"
    ipv4_gateway = "10.10.20.1"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  manage_user_account = false

  tags = ["automation", "container", "haproxy1", "lxc", "ubuntu"]
}

module "rabbit_test_mail_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "test-mail.ddlns.net"
  vmid        = 804
  node_name   = "rabbit-01-psp"
  description = "test-mail.ddlns.net"
  console     = {}

  cpu_cores      = 2
  memory         = 2048
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "debian"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:F4:F9:86"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "10.10.20.103/24"
    ipv4_gateway = "10.10.20.1"
    ipv6_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = false

  manage_user_account = false

  tags = ["mail"]
}

module "rabbit_satisfactory_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "satisfactory.ddlns.net"
  vmid        = 805
  node_name   = "rabbit-01-psp"
  description = "Satisfactory Container"

  cpu_cores      = 4
  memory         = 12288
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd2"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:56:15:A6"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  manage_user_account = false

  tags = ["automation", "container", "lxc", "satisfactory", "ubuntu"]
}

module "rabbit_graylog_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "graylog.ddlns.net"
  vmid        = 807
  node_name   = "rabbit-01-psp"
  description = "graylog.ddlns.net"

  cpu_cores      = 8
  cpu_limit      = 4
  memory         = 16384
  swap           = 0
  disk_size      = 80
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:41:A8:4A"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  console = {}

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = false

  manage_user_account = false

  tags = ["automation", "lxc"]
}

module "rabbit_pbs_01_psp_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "pbs-01-psp.ddlns.net"
  vmid        = 802
  node_name   = "rabbit-01-psp"
  description = "pbs-01-psp.ddlns.net"

  cpu_cores      = 4
  memory         = 4096
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "debian"

  network_bridge         = "vmbr0"
  network_mac_address    = "BC:24:11:D1:13:50"
  network_interface_name = "eth0"
  network_firewall       = true

  ip_config = {
    ipv4_address = "192.168.122.101/24"
    ipv4_gateway = "192.168.122.1"
  }

  console = {}

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  manage_user_account = false

  tags = ["backup"]
}

module "rabbit_squid_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "squid.ddlns.net"
  vmid        = 801
  node_name   = "rabbit-01-psp"
  description = "Squid Proxy Container for content filtering"

  cpu_cores      = 2
  memory         = 2048
  swap           = 0
  disk_size      = 20
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr2"
  network_mac_address    = "BC:24:11:E3:04:A9"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "10.10.40.100/24"
    ipv4_gateway = "10.10.40.1"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  manage_user_account = false

  tags = ["automation", "container", "lxc", "proxy", "ubuntu"]
}

module "rabbit_rtmp1_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "rtmp1.ddlns.net"
  vmid        = 803
  node_name   = "rabbit-01-psp"
  description = "rtmp1.ddlns.net"

  cpu_cores      = 8
  memory         = 8192
  swap           = 0
  disk_size      = 30
  disk_datastore = "data-ssd2"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "62:F1:59:86:4E:CC"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  console = {}

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  manage_user_account = false

  tags = ["automation", "lxc"]
}

module "rabbit_mon_bgy_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname    = "mon-bgy.ddlns.net"
  vmid        = 808
  node_name   = "rabbit-01-psp"
  description = "Proxmox monitoring - BGY site (pve-exporter + Grafana Alloy)"

  cpu_cores      = 1
  cpu_limit      = 1
  memory         = 512
  swap           = 0
  disk_size      = 4
  disk_datastore = "data-ssd"

  template_file_id = proxmox_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  console = {}

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  manage_user_account = false

  tags = ["automation", "lxc", "monitoring"]
}
