{
 "title": "AWX — k8s-vms-daniele",
 "tags": [
  "k8s-vms-daniele",
  "awx",
  "ansible",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "awx_database_connections_total{cluster=\"k8s-vms-daniele\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "awx_system_info{cluster=\"k8s-vms-daniele\"}"
      }
     ]
    },
    {
     "title": "Controller Node Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(awx_instance_info{cluster=\"k8s-vms-daniele\"})",
       "legendFormat": "  "
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs and Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "job status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "awx_status_total{cluster=\"k8s-vms-daniele\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Job Status per Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "awx_instance_status_total{cluster=\"k8s-vms-daniele\"}",
       "legendFormat": "{{node}}-{{status}}"
      }
     ]
    },
    {
     "title": "Remaining Instance Capacity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "awx_instance_remaining_capacity{cluster=\"k8s-vms-daniele\"}",
       "legendFormat": "remaining_capacity_{{hostname}}"
      }
     ]
    },
    {
     "title": "Consumed Instance Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "awx_instance_consumed_capacity{cluster=\"k8s-vms-daniele\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}