{
 "title": "Cloudflare Tunnel — k8s-vms-daniele",
 "description": "Display Statistics for your Cloudflare Tunnels (cloudflared)",
 "tags": [
  "k8s-vms-daniele",
  "cloudflared",
  "networking",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cloudflare Edge Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections{cluster=\"k8s-vms-daniele\",job=\"cloudflared\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "description": "Concurrent requests proxied through each tunnel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel{cluster=\"k8s-vms-daniele\",job=\"cloudflared\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response By Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(cloudflared_tunnel_response_by_code{cluster=\"k8s-vms-daniele\",job=\"cloudflared\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(cloudflared_tunnel_total_requests{cluster=\"k8s-vms-daniele\",job=\"cloudflared\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Config Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(cloudflared_orchestration_config_version{cluster=\"k8s-vms-daniele\",job=\"cloudflared\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(cloudflared_tunnel_request_errors{cluster=\"k8s-vms-daniele\",job=\"cloudflared\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}