{
 "title": "Falco — k8s-vms-daniele",
 "description": "Grafana dashboard for Falco output events",
 "tags": [
  "k8s-vms-daniele",
  "falco",
  "security",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "priority",
    "label": "Priority",
    "query": {}
   },
   { "name": "top", "label": "Top", "query": "5,10,20,50" },
   { "name": "searchpattern", "label": "Search-Pattern" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"falco\",cluster=\"k8s-vms-daniele\",priority=~\"$priority\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source) (count_over_time({service_name=\"falco\",cluster=\"k8s-vms-daniele\",priority=~\"$priority\"}[$__range]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Priorities",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (priority) (count_over_time({service_name=\"falco\",cluster=\"k8s-vms-daniele\",priority=~\"$priority\"}[$__range]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rule) (count_over_time({service_name=\"falco\",cluster=\"k8s-vms-daniele\",priority=~\"$priority\"}[$__range]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Events rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (priority) (count_over_time({service_name=\"falco\",cluster=\"k8s-vms-daniele\",priority=~\"$priority\"}[1m]))",
     "legendFormat": "{{priority}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Top $top Pods",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (k8s_pod_name,k8s_ns_name) (\n  count_over_time({service_name=\"falco\",cluster=\"k8s-vms-daniele\",priority=~\"$priority\",priority!=\"Debug\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{service_name=\"falco\",cluster=\"k8s-vms-daniele\",priority=~\"$priority\"} |~ \"(?i)$searchpattern\"\n| line_format `{{ if eq .priority \"Emergency\" }} ❌ {{ else if eq .priority \"Alert\" }} ❌ {{ else if eq .priority \"Critical\" }} ❌ {{ else if eq .priority \"Error\" }} 🔴 {{ else if eq .priority \"Warning\" }} 🟠 {{ else if eq .priority \"Notice\" }} 🟡 {{ else if eq .priority \"Informational\" }} 🔵 {{ else if eq .priority \"Debug\" }} 🟣 {{__line__}} {{else}} ⚪ {{end}} {{__line__}}`"
      }
     ]
    }
   ]
  }
 ]
}