{
 "title": "Flux — k8s-vms-daniele",
 "tags": [
  "k8s-vms-daniele",
  "flux",
  "gitops",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",phase=\"Running\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Max Work Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\"})",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",container!=\"\",container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\"}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Kubernetes API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",code!~\"2..\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reconciliation Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Reconciliation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",name=\"kustomization\"}",
     "legendFormat": "kustomizations"
    }
   ]
  },
  {
   "title": "Cluster Reconciliations ops/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"kustomization\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful reconciliations "
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"kustomization\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed reconciliations "
    }
   ]
  },
  {
   "title": "Sources Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Git Repos ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"gitrepository\",result!=\"error\"}[1m]))",
     "legendFormat": "successful git pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"gitrepository\",result=\"error\"}[1m]))",
     "legendFormat": "failed git pulls"
    }
   ]
  },
  {
   "title": "OCI Repos ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"ocirepository\",result!=\"error\"}[1m]))",
     "legendFormat": "successful oci pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"ocirepository\",result=\"error\"}[1m]))",
     "legendFormat": "failed oci pulls"
    }
   ]
  },
  {
   "title": "Helm Repos ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"helmrepository\",result!=\"error\"}[1m]))",
     "legendFormat": "successful helm pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"helmrepository\",result=\"error\"}[1m]))",
     "legendFormat": "failed helm pulls"
    }
   ]
  },
  {
   "title": "Buckets ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"bucket\",result!=\"error\"}[1m]))",
     "legendFormat": "successful bucket pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"bucket\",result=\"error\"}[1m]))",
     "legendFormat": "failed bucket pulls"
    }
   ]
  },
  {
   "title": "Helm Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  { "title": "Helm Release Duration", "type": "timeseries", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 }, "fieldConfig": { "defaults": { "unit": "s" } } },
  {
   "title": "Helm Releases ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"helmrelease\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful reconciliations "
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"helmrelease\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed reconciliations "
    }
   ]
  },
  {
   "title": "Helm Charts ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"helmchart\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful chart pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"k8s-vms-daniele\",namespace=\"flux-system\",controller=\"helmchart\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed chart pulls"
    }
   ]
  }
 ]
}