---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-deploy
  namespace: sysdig-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: sysdig-deploy
      version: 1.3.25
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
  - chartFileRef:
      path: ../clusters/common/sysdig-agent/release.yml
  values:
    global:
      clusterConfig:
        name: "k8s-daniele-vms"
      sysdig:
        region: "us1"

    agent:
      resourceProfile: custom
      resources:
        requests:
          cpu: 300m
          memory: 600Mi
        limits:
          cpu: 500m
          memory: 1Gi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: "NoSchedule"
          key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
      sysdig:
        settings:
          prometheus:
            enabled: true
            prom_service_discovery: true

    nodeAnalyzer:
      nodeAnalyzer:
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          - effect: "NoSchedule"
            key: "CriticalAddonsOnly"
            operator: "Equal"
            value: "true"
        benchmarkRunner:
          resources:
            limits:
              cpu: 250m
        runtimeScanner:
          resources:
            limits:
              cpu: 300m
