---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-deploy
  namespace: sysdig-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: sysdig-deploy
      version: 1.3.25
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      clusterConfig:
        name: "k8s-daniele-vms"
      sysdig:
        accessKeySecret: "sysdig-agent"
        region: "us1"
      image:
        registry: quay.io

    agent:
      #image:
      #  tag: 12.8.1
      enabled: true
      resourceProfile: custom
      resources:
        requests:
          cpu: 300m
          memory: 600Mi
        limits:
          cpu: 500m
          memory: 1Gi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: "NoSchedule"
          key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
      sysdig:
        settings:
          app_checks_enabled: false
          feature:
            mode: monitor
          jmx:
            enabled: false
          log:
            rotate: 20
            max_size: 20
            console_priority: warning
            file_priority: debug
            file_priority_by_component:
              - "promscrape: warning"
              - "promscrape:prom_emitter: warning"
              - "watchdog_runnable: warning"
              - "sdjagent: warning"
              - "mountedfs_reader: warning"
          #metrics_filter:
          #  - include: container_fs*
          #  - exclude: container_*
          prometheus:
            enabled: true
            prom_service_discovery: true
          #skip_events_by_process:
          #  - fluent-bit
          #skip_events_by_type:
          #  - recvfrom

    nodeAnalyzer:
      nodeAnalyzer:
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          - effect: "NoSchedule"
            key: "CriticalAddonsOnly"
            operator: "Equal"
            value: "true"
        benchmarkRunner:
          resources:
            limits:
              cpu: 250m
        runtimeScanner:
          deploy: true
          resources:
            limits:
              cpu: 300m
          settings:
            eveEnabled: true
      secure:
        vulnerabilityManagement:
          newEngineOnly: true

    rapidResponse:
      enabled: true
      rapidResponse:
        existingPassphraseSecret: "sysdig-rapid-response"
