---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ansible-awx
  namespace: awx
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: awx-chart
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    AWX: 
      enabled: true
      name: awx
      spec:
        ingress_type: ingress
        hostname: ansible.fastnetserv.net
        image: ansible/awx
        image_version: 17.0.1
        image_pull_policy: Always
        projects_persistence: true
        projects_storage_class: local-path
        projects_storage_size: 8Gi
        projects_storage_access_mode: ReadWriteOnce
        web_resource_requirements:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
        task_resource_requirements:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ee_resource_requirements:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi