---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ansible-awx
  namespace: awx
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: awx-chart
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
