apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: charts
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc-test/apps
  prune: true
