---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: infrastructure
  secretRef:
    name: slack-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: fluxcd-notifications
  namespace: flux-system
spec:
  summary: "cluster status"
  providerRef:
    name: slack
  eventMetadata:
    env: "production"
    cluster: "kubenuc"
    region: "milan"
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: charts
    - kind: HelmRelease
      name: '*'
#    - kind: Kustomization
#      name: '*'