---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pangolin-newt-kubenuc-harbor
  namespace: pangolin-newt
spec:
  itemPath: "vaults/66qfxcmgwlhutunx6slav6fyve/items/pangolin-newt-kubenuc-harbor"
