---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jfrog
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/jfrog-acr/manifests
  prune: true
  patches:
    - target:
        kind: HelmRelease
        name: artifactory
      patch: |
        - op: replace
          path: /spec/values/artifactory/artifactory/size
          value: "2Gi"
