checks:
  doNotAutoAddDefaults: true
  include:
    - cluster-admin-role-binding
    - docker-sock
    - host-ipc
    - host-network
    - host-pid
    - latest-tag
    - no-read-only-root-fs
    - privilege-escalation-container
    - privileged-container
    - run-as-non-root
    - writable-host-mount
