apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: karakeep-nextauth-secret
  namespace: karakeep
spec:
  itemPath: "vaults/k8s_secrets/items/karakeep_nextauth_secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: karakeep-meili-master-key
  namespace: karakeep
spec:
  itemPath: "vaults/k8s_secrets/items/karakeep_meili_master_key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: karakeep-openai-api-key
  namespace: karakeep
spec:
  itemPath: "vaults/k8s_secrets/items/karakeep-openai-api-key"
