---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sendgrid-exporter
  namespace: flux-system
spec:
  targetNamespace: sendgrid
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/sendgrid/manifests
  prune: true
