---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: intel-device-plugin-operator
  namespace: intel-gpu-plugin
spec:
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.29.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 6
      strategy: rollback
