---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-alloy-secrets
  namespace: flux-system
spec:
  targetNamespace: grafana-alloy
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/k8s-vms-daniele/apps/grafana-alloy/secrets
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-alloy
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-vars
    - name: grafana-alloy-secrets
  targetNamespace: grafana-alloy
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/k8s-vms-daniele/apps/grafana-alloy/manifests
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: grafana-k8s-monitoring
      namespace: grafana-alloy
