---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-secrets
  namespace: flux-system
spec:
  targetNamespace: forgejo
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/forgejo/secrets
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-vars
    - name: openebs
    - name: forgejo-secrets
    - name: postgresql-db
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/forgejo/manifests
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: forgejo
      namespace: forgejo
