---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart pve-exporter
  ansible.builtin.systemd:
    name: pve-exporter
    state: restarted

- name: Restart alloy
  ansible.builtin.systemd:
    name: alloy
    state: restarted
