---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-scanner-secret
  namespace: flux-system
spec:
  targetNamespace: sysdig-agent
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/sysdig-harbor-scanner/secrets
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-scanner
  namespace: flux-system
spec:
  dependsOn:
    - name: harbor-scanner-secret
    - name: harbor
    - name: sysdig-agent
  targetNamespace: sysdig-agent
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/sysdig-harbor-scanner/manifests
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: sysdig-harbor-scanner
      namespace: sysdig-agent
