---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-scanner-sysdig-secure
  namespace: harbor-scanner-sysdig-secure
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor-scanner-sysdig-secure
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    sysdig:
      secure:
        existingSecureAPITokenSecret: "harbor-scanner-sysdig-secure"
        url: "https://eu1.app.sysdig.com"
