#ENC[AES256_GCM,data:4a796rdCkgJZ5KvQeMWf8vwye9ew7cI/o1qQfv/DB3VE1fqzvfTnMfPV2wtU0x6ZqRA695QGTDoI,iv:bg6lkAr6OIoITz3JE4LB1GdmoTChjCYI9qba2b1Leic=,tag:lNBHnJrh9A2tfng+Ntq26w==,type:comment]
#ENC[AES256_GCM,data:tsiIe+K3VCOBbdptH9uojkW9tEzz7PHk1SznWlOuUUT1RmBbmJ67T+4fkgzM6jNQ2+Lf8nyBKXAvA2UNGqw3W95s1NmnHy2MBkg2Narh,iv:OSJxv6/YJoMMplu3hC+cJSvYvQTr/ZPR+vJtDB8U7/s=,tag:3s3PpzCnARPlI5PIw9tKxQ==,type:comment]
#
#ENC[AES256_GCM,data:PYuks2Zb3/8gVvSiOCBsejtHx90Ca2uZCaWG4i1rKB5RuNyx0op4qQ==,iv:w1g4EFSmkDJmVIp5mHOOKOEm0aal8+Cv+kpJ2QfwZV8=,tag:OKQ+TEIiWWu/GRb+4ttygQ==,type:comment]
#ENC[AES256_GCM,data:ZtrXbPW+GuxMTe+IdQhj3RP2EZGrS5Fbj64/7kPCE+Fc32IY,iv:kLvhrzYBF2daMMbWNtWuUF5viOIDeVqYCJo/6wmH9d0=,tag:9c0oCAL0HEaPT+qi+MRTFA==,type:comment]
#ENC[AES256_GCM,data:NY9jL6nj/eP5C2KAyQvt+/due27k9BqTs8ay5lxh7jUbNOdfkQJmWDU6ig==,iv:mqBXD1SgZh6BEZe0u1aQZ1Dl+FXMlpVpA3C2WKumiew=,tag:kY8+Mwp4VZPfETtjGP0xag==,type:comment]
#ENC[AES256_GCM,data:8uPpHl2ud01rrruyz+wtacvO6i+t/wCz9g8atK34,iv:GXUV4CIcqXl6/5TkL0A0rwKJeRBqFPJDzB8s/wla/sQ=,tag:IvLgd42itEPyvgx8GoOM2Q==,type:comment]
#ENC[AES256_GCM,data:BHu7A5ptFFIG6ZQLX9A/+QVw7WQBb8mV6r6QH+hRo5Wrb2OdVVyfukI9/UQD6x44gw==,iv:2x4rLmJaCQlF6FFXryxMPpfXmixvivHy8Idpd2eH4hc=,tag:AV9/K82UpcAhS3S1Mc7oUQ==,type:comment]
#ENC[AES256_GCM,data:vmAFhZ+wsjGPNqxTD3p7y9WD8Tp+QmM53Gd1zyUXpohOrQ==,iv:f6IU+9KajZF2/i5jvrltvZNKthk7GTbjmpTNrSmjFMs=,tag:hJYAt/Gmwq3oxWVnR8aAAg==,type:comment]
#ENC[AES256_GCM,data:XUGOZnrzdQvUYX98Dv9H5ql9BipwFWSo+aUN2/HeL/+M5uaDLErAsdC32c5vmHW2d8m97KlIBem4FKlOBiAhViWlDw==,iv:gAhoFlXeOC8KDg8DqnrkB2I4oKD8+ml5n/8qMb2LEJY=,tag:fFNlOAYFNAuDl/BCjY+Lug==,type:comment]
#ENC[AES256_GCM,data:cF1hEQGJovta72Rr4X54HvTXkbOJ+vcV4LaZtlc2gA1U1d20I8XQuVhdhKnIXHHH9amSdHO80kV0Mg==,iv:r1Qupd5tvigQFj+rQvg2NNPFT+1WOargcCa5R9gYqXA=,tag:jFf3e8oziYXCZ4jCTTlBVQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:PXU=,iv:VTg7oRVgnhvDjE0jNOiFt6IfC18/aEfuXOZHfmUetNM=,tag:RacQ26C3/khzullu54nFNg==,type:str]
kind: ENC[AES256_GCM,data:p89+ny5f,iv:JPjjKZ+E1dyA71k8h1thP2ea5EFDgM/jJnuOl8fHpsw=,tag:OqRLul2rCvQpC+o8eQr/Vg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mI2umsluWmxs3DEx,iv:dmXp6zhHsd12h2LJWhUYpDYeApilcfiS7hSdp0y5lAY=,tag:h+FN+Lkrq6VJu2c5ShuOJg==,type:str]
    namespace: ENC[AES256_GCM,data:GmDPl3gTUeuDQK8=,iv:OhMhnHklPwLL7ojqd8ZvmLktYLoqDhpD0Nc9+ZA1sjM=,tag:01DhxoW+YZxaBERgMT28TA==,type:str]
stringData:
    TELEPORT_HOST: ENC[AES256_GCM,data:KThrRDopZA6mys4IvfcrHz4P,iv:YlU5aJKru/2TatIOH4MNMzBpJcdpFKlwPJLNsCuuxgQ=,tag:QQCotBloA+zzt6NDYjMjeQ==,type:str]
    NGX_WEBHOOK_HOST: ENC[AES256_GCM,data:hz2bGaPDnauzcXkGJMoyuws=,iv:9vS0k4GnIxo5sU1KPxj5WFWR4fLAz03IktT6KAT3m+w=,tag:ovODZete8EOnNA+/wO+RLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVEo1T2dlUWZJaklDWEtV
            cHA5T0dXT2szUFRGTVE2QW5va3pEbHR2ejFvCjA2ZzhtTWcxeDlVMkNqTjhsc2du
            T1RuR2plbVpkVTJ2Sno3YTR0dUJtN2sKLS0tIHB2Sy9ST0RRdkRTNXZnT0puUWpE
            K3Job1VYenMxTTloL2Fqb2Y1N1lTMTgKcpIUXydTZnWsid51GBBrDipwPgIuvkUg
            76HelYMXEEdK+zcp1tFvr0tRVE0CwALJi8xwJ4mwnrvQuoiq4hbP2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13fpkwl74k6lttn534vthcq08mr2r684067e2p9yw9h0w5j967g3qlsydgm
    lastmodified: "2026-08-09T08:02:02Z"
    mac: ENC[AES256_GCM,data:qQDnRK5vgFSjPkaN8LAz8qXoLAdtxPrL7hUNSiEKeG9jkDwNtqo40VpsbO+ALA8nkj/27CpH6ITIQbtwLYdros16kBtG+l4UsLofBJmI2aZt4Sjrsw8EbQj2ogLbMqktPjtx+bxpe4JsUrVZXZMsWUjaW45YbF+1DeuE++3LZqk=,iv:nPpKBuwiJx9zUB8qXPhjJkzieHVPBhEXLWgKqyubS58=,tag:2NhC9qM8eSqtBsfTb1nEGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
