---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage-s3
  namespace: flux-system
spec:
  dependsOn:
    - name: openebs
  targetNamespace: nextcloud-fastnetserv
  path: ./clusters/kubenuc/apps/s3/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 15m
  patches:
    - target:
        kind: HelmRelease
        name: garage-s3
      patch: |
        - op: replace
          path: /spec/values/garage/replicationMode
          value: "1"
        - op: replace
          path: /spec/values/deployment/replicaCount
          value: 1
        - op: replace
          path: /spec/values/persistence/data/size
          value: 1Gi
