---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-object-store-credentials
  namespace: databases
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_ENDPOINT: http://test
  AWS_S3_FORCE_PATH_STYLE: "true"
  WAL_S3_BUCKET: test
