---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: unifi
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi-poller
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    env:
      TZ: Europe/Rome
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: unifi-poller-secret
        subPath:
          - path: up.conf
            mountPath: /etc/unifi-poller/up.conf
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9130"
      prometheus.io/path: "/metrics"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    env:
      TZ: Europe/Rome
    ingress:
      main:
        ingressClassName: nginx
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - host: unifi.ddlns.net
            paths:
              - path: /
                pathType: Prefix
            tls:
              - secretName: unifi-ssl
                hosts:
                  - unifi.ddlns.net
    persistence:
      data:
        enabled: true
        mountPath: /unifi
        storageClass: local-hostpath
