---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    image:
      tag: v6
    env:
      TZ: Europe/Rome
    ingress:
      main:
        ingressClassName: nginx
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: unifi.ddlns.net
            paths:
              - path: /
                pathType: Prefix
            paths:
              - path: /inform
                pathType: Prefix
                service:
                  name: main
                  port: controller
        tls:
          - secretName: unifi-ssl
            hosts:
              - unifi.ddlns.net
    persistence:
      data:
        enabled: true
        mountPath: /unifi
        storageClass: local-hostpath
        accessMode: ReadWriteOnce
        size: 10Gi
