all:
  children:
    teleport_client:
      hosts:
        mon-bgy:
          ansible_host: <mon-bgy-ip>
          teleport_labels:
            site: bgy
            role: monitoring-node

        mon-lug:
          ansible_host: <mon-lug-ip>
          teleport_labels:
            site: lug
            role: monitoring-node

        mon-mxp:
          ansible_host: <mon-mxp-ip>
          teleport_labels:
            site: mxp
            role: monitoring-node
