---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets
  namespace: harbor
type: Opaque
stringData:
  password: testpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password-secret
  namespace: harbor
type: Opaque
stringData:
  redis-password: testpassword
