apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sysdig-agent
spec:
  itemPath: "vaults/k8s_secrets/items/Agent_US-East"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sysdig-rapid-response
spec:
  itemPath: "vaults/k8s_secrets/items/Rapid_Response_US-East"
