apiVersion: v1
kind: Secret
metadata:
    name: onepassword-secret
    namespace: 1password
stringData:
    token: ENC[AES256_GCM,data:Ihx5G81CbZZZUXNGqI15/kdC8nvh5bXDPkubh4jGJwhPCu8wWaZGI3YYvlCVerNxrj7uJkGcEVsqxoTJGs3kCbNmr3qJv3KUhm6T3Py/watqXy44clxGHqh9k3r9YdNxQZ0VKzWayZb4MOpkvxpWeaG3uKJaR0QtDur6TaMX/T3CYbVxEWCmJR94echWs5Q3/s1FyO69tQgurqhNtlXakg6+L5GVulJTVVVQ9c4YnkKgxgXmBObZmLAcShldqVi3UfTjbimEYwTDifJivlc6BxWVS1nFZyn9ou0VTvbIkIGpT+yQyzd1S+tng06OTUMF8R7rC4jubOm/QKgFjfvuLrgWciMBE7ZFQHO2UkOGUrqZJhV6iISy4WUX9pRjzJqiT4vcF2dua5EIqLjJedsIzzn4dDVs9Dw/xL42ktqy6dlg70vECaAXhoiSs/iYmzhXdAhdb/WsysBnlepMV6JwTn7gNVLoadh7k5Mi0NXDfI9FIDWn9RG5Yb+nMLu8mwAPIFuA+XsUf8FhyGIbgPdSsNuQH0c354ctt3ie6Ozhru62u3x6Iw3Yhv8jOvIyw9pT3ggC3C193XfwcuGEmsLgKTvCKhnDFbNWveIvavhI1HmrnZorH5fKLt9tPZoc6/EH6NU08QS+sY1MzcPFaVy9yTxH79ZgVUP7nMEABVR1l9l2dUrm5NbTZBHWrn+Xn2Bamt0bAuG3wZUT1laUl+JNnLd+49P/4zTI9hdsXgFMMk3y/+94b7I6RGFfQi8frtoVaM2sWg33ZUEPFM4OzGBVytlM4JpFR3XaHXwYMNIULp+KSnwFyCvZ6G/o+628QNuCrCJB/4Wyq5+W1r1LwZanNqF6,iv:O95nVHPcjU7fjtIhs6/NCJ0MCm74OsUK5Th1EcINDuY=,tag:eUiWdlGn363JkoxKuHS6QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYzhUNDBpOGpWQSt0V1NF
            VSt4UFR0WmZ1eG9CVURGa0lWbDh3ek9rT2s4CmhFQmlSSG9QTnZ5YXJjZVB6WlpN
            WFd6M253UG5CTXh3QUY1UDFyUldiaHcKLS0tICtDc0cyMFkzWndhakhXOUFTYnoz
            bE1GdEhENERJdkJhc29KQTM2UmtSWVEK3N18ZMKMEXO5GCU6zohEKA0asKjfH+2o
            2fup6oy+fcrYxwa/vRqO/B1zsq85iFDiC/gl82ruLRQzqtwy10+EHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwhpwjgw3c7trgrtjv7k309suma9l6qu8yrh4at80clrymrczvss8xq69u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T16:34:10Z"
    mac: ENC[AES256_GCM,data:8NUEd8TIxG49nL93bwvnAMFtOS+eVvUNxROJiX3DezvelnLJ0m47L5o6R1v/ZJKQqBK/lyh7qn6460wE2rLADxJqIMQxLSh1mFTtc2OwY8jgk8aKpP01LgCpAAAT+NGotuJp9GS8VsT2vNIarQMC1FnYq0Oyn9q/Qngp7cUSX9E=,iv:RA4nfgCJ8RYqUsr60sumC755kWYjAb7Q7lpNisT17sw=,tag:tUuKqfB45AXRrBQAcU1jxw==,type:str]
    version: 3.13.3
