apiVersion: v1
kind: Secret
metadata:
    name: onepassword-secret
    namespace: 1password
stringData:
    token: ENC[AES256_GCM,data:oMMid+iM/zdaB4xLaXgCD+A1rvucGA9j3QSWBOCeDk3jXgqISs0p3+4=,iv:4qUaKEaiqK9pmZ/GuPpwXalREJTqsRnBydmXsp/yPCU=,tag:pd+sjydubvR9MXzrKYY82w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbyt3QTJzSXcyWjZYb25G
            eGlEZjZIcWh2ZHNMWTQzSXRBWWtUOGx4KzNvCk5ISHl3NE9XYkxrODE5RVhUcERo
            ZjNxMkJDSDQzUWhSY0xvZjVpd0s3ZHcKLS0tIHAzNXJuUDFpd2V0T3hScjlvTVlC
            UXM0SnBjRUE2VVdRb0VQenZOcFA3NTAKUqzaqIDjaoeSYtOlyWuAbFV5L1VJZycv
            qmaqK1hAocPvW4hHnUqhPVHXTt6r+jhbU7Fino35MoigQbBKQPTJig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwhpwjgw3c7trgrtjv7k309suma9l6qu8yrh4at80clrymrczvss8xq69u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T16:18:11Z"
    mac: ENC[AES256_GCM,data:xUgbKLuTU92Ndo/sgVAOk7O2aX3eYgu3bDxJtQhl1SCSAqT5MQxCovbCu7pI1GbFgvMU/NZcjs+iMnGILrWVCY+p5hNAUTxTV1827PtFepmoSWPM4PqmutosDdYZw6WOtXbWld1hb70SrsPbyOhFtBNzUkx41FblVGR3Ueo9qEw=,iv:xUFX35YnU0JejMX40iRNfuJXpIiWaDcxuAjJZRfK+yA=,tag:JgUB2OUZ3bsjAqv7GXJvxg==,type:str]
    version: 3.13.3
