apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1password/deploy.yaml
  - 1password/namespace.yaml
  - flux-operator/deploy.yaml
  - fluxcd
  - system-upgrade-controller/deploy.yaml
  - teleport-agent/deploy.yaml
