---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: ">=10.2.5 < 11.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami-chart
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    ingress:
      annotations: 'cert-manager.io/cluster-issuer: letsencrypt'
      enabled: true
      hostname: jenkins.ddlns.net
      tls: true
    jenkinsUser: admin
    service:
      type: ClusterIP