---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ansible-awx
  namespace: awx
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: ">=0.25.0"
      sourceRef:
        kind: HelmRepository
        name: awx-chart
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    AWX: 
      enabled: true
      name: awx
      spec:
        ingress_type: ingress
        hostname: ansible.fastnetserv.net
        secret_key_secret: custom-awx-secret-key
        projects_persistence: true
        projects_storage_class: local-path
        projects_storage_size: 8Gi
        projects_storage_access_mode: ReadWriteOnce
        web_resource_requirements:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        task_resource_requirements:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 300m
            memory: 1Gi
        ee_resource_requirements:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
