---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-deploy
  namespace: sysdig-agent
spec:
  maxHistory: 20
  interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
    timeout: 30m
  upgrade:
    remediation:
      retries: 50
    timeout: 30m
  chart:
    spec:
      chart: shield
      version: ">=0.9.4"
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
  values:
    cluster_config:
      name: k8s-daniele-vms
    sysdig_endpoint:
      region: us1
      access_key_existing_secret: "sysdig-agent"
      secure_api_token_existing_secret: "sysdig-agent-api"
    host:
      driver: universal_ebpf
      resources:
        shield:
          requests:
            cpu: 300m
            memory: 600Mi
          limits:
            cpu: 500m
            memory: 1Gi
      additional_settings:
        feature:
          mode: troubleshooting
        tags: cluster:k8s-daniele-vms,location:Swiss
        cri:
          socket_path: /run/k3s/containerd/containerd.sock
        log:
          #file_priority: info
          #console_priority: info
          #event_priority: info
          file_priority: warning
          console_priority: warning
          event_priority: warning
          #file_priority_by_component:
          #  - "cm_socket_endpoint: debug"
          #  - "endpoint: debug: debug"
          #  - "conn_mgr: debug: debug"
          #  - "connection_manager: debug"
          #  - "cm_collector_endpoint: debug"
    features:
      monitoring:
        prometheus:
          enabled: true
          prometheus_yaml:
            global:
              scrape_interval: 10s
            scrape_configs:
            - job_name: blackbox
              metrics_path: /probe
              params:
                module:
                - http_2xx
              relabel_configs:
              - source_labels:
                - __address__
                target_label: __param_target
              - source_labels:
                - __param_target
                target_label: instance
              - replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115	# Blackbox hostname:port
                target_label: __address__
              static_configs:
              - targets:
                - https://harbor.ddlns.net
                labels:
                  kube_namespace_name: 'ciccio'
            - job_name: kubernetes-blackbox-services
              kubernetes_sd_configs:
              - role: service
              metrics_path: /probe
              params:
                module:
                - http_2xx
              relabel_configs:
              - action: keep
                regex: true
                source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_probe
              - source_labels:
                - __address__
                target_label: __param_target
              - replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115	# Blackbox hostname:port
                target_label: __address__
              - source_labels:
                - __param_target
                target_label: instance
              - action: labelmap
                regex: __meta_kubernetes_service_label_(.+)
              - source_labels:
                - __meta_kubernetes_namespace
                target_label: kube_namespace_name
              - source_labels:
                - __meta_kubernetes_service_name
                target_label: kube_service_name
      posture:
        cluster_posture:
          enabled: true
        host_posture:
          enabled: true
      responding:
        rapid_response:
          # Disable on 0.3.1 it's not supported the password in an external secret
          enabled: false
      vulnerability_management:
        container_vulnerability_management:
          enabled: true
        host_vulnerability_management:
          enabled: true
        in_use:
          enabled: true
      detections:
        drift_control:
          enabled: true
        malware_control:
          enabled: true
        ml_policies:
          enabled: true
        kubernetes_audit:
          enabled: true
      admission_control:
        enabled: false
      investigations:
        activity_audit:
          enabled: true
        live_logs:
          enabled: true
        captures:
          enabled: true
