apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: charts
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/kubenuc
  prune: true
  wait: true
  timeout: 5m0s
