---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: pve-monitoring-test
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      pve-monitoring-test:
        ansible_python_interpreter: /usr/bin/python3
        pve_token_id: "monitoring@pve!exporter"
        pve_node_label: test
        pve_targets:
          - 127.0.0.1:8006
verifier:
  name: ansible
