# Auto-generated imports for hpelvisor
# Generated by proxmox-generate-tf.py

import {
  to = module.hpelvisor_gitlab_ddlns_net_lxc.proxmox_virtual_environment_container.this
  id = "hpelvisor/700"
}

import {
  to = module.hpelvisor_dolibarr_test_bioadventures_eu_lxc.proxmox_virtual_environment_container.this
  id = "hpelvisor/701"
}

import {
  to = module.hpelvisor_gen8_runner_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/3000"
}

import {
  to = module.hpelvisor_sensor_debian12_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/703"
}

import {
  to = module.hpelvisor_pelican_game_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/7003"
}

import {
  to = module.hpelvisor_prod_k3s_worker1_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/601"
}

import {
  to = module.hpelvisor_openstack_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/900"
}

import {
  to = module.hpelvisor_openstack_snap_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/2000"
}

import {
  to = module.hpelvisor_sensor_ubuntu24_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/702"
}

import {
  to = module.hpelvisor_prod_k3s_master_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/600"
}

import {
  to = module.hpelvisor_amp_game_vm.proxmox_virtual_environment_vm.this
  id = "hpelvisor/7000"
}
