# Auto-generated resources for rabbit-01-psp
# Generated by proxmox-generate-tf.py
# Review and adjust as needed before applying

module "rabbit_satisfactory_shared_ddlns_net_lxc" {
  source = "../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname        = "satisfactory-shared.ddlns.net"
  vmid            = 806
  node_name       = "rabbit-01-psp"
  description     = "satisfactory-shared.ddlns.net"

  cpu_cores       = 4
  memory          = 12288
  swap            = 0
  disk_size       = 30
  disk_datastore  = "data-ssd2"

  template_file_id = proxmox_virtual_environment_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:91:18:13"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  tags = ["automation", "container", "lxc", "satisfactory", "ubuntu"]
}

module "rabbit_haproxy1_ddlns_net_lxc" {
  source = "../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname        = "haproxy1.ddlns.net"
  vmid            = 800
  node_name       = "rabbit-01-psp"
  description     = "haproxy1.ddlns.net"

  cpu_cores       = 4
  memory          = 2048
  swap            = 0
  disk_size       = 20
  disk_datastore  = "data-ssd"

  template_file_id = proxmox_virtual_environment_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:D1:06:0F"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "10.10.20.172/24"
    ipv4_gateway = "10.10.20.1"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  tags = ["automation", "container", "haproxy1", "lxc", "ubuntu"]
}

module "rabbit_test_mail_ddlns_net_lxc" {
  source = "../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname        = "test-mail.ddlns.net"
  vmid            = 804
  node_name       = "rabbit-01-psp"
  description     = "test-mail.ddlns.net"

  cpu_cores       = 2
  memory          = 2048
  swap            = 0
  disk_size       = 30
  disk_datastore  = "data-ssd"

  template_file_id = proxmox_virtual_environment_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "debian"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:F4:F9:86"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "10.10.20.103/24"
    ipv4_gateway = "10.10.20.1"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = false

  tags = ["mail"]
}

module "rabbit_satisfactory_ddlns_net_lxc" {
  source = "../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname        = "satisfactory.ddlns.net"
  vmid            = 805
  node_name       = "rabbit-01-psp"
  description     = "satisfactory.ddlns.net"

  cpu_cores       = 4
  memory          = 12288
  swap            = 0
  disk_size       = 30
  disk_datastore  = "data-ssd2"

  template_file_id = proxmox_virtual_environment_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:56:15:A6"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = true

  tags = ["automation", "container", "lxc", "satisfactory", "ubuntu"]
}

module "rabbit_graylog_ddlns_net_lxc" {
  source = "../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname        = "graylog.ddlns.net"
  vmid            = 807
  node_name       = "rabbit-01-psp"
  description     = "graylog.ddlns.net"

  cpu_cores       = 8
  memory          = 8192
  swap            = 0
  disk_size       = 50
  disk_datastore  = "data-ssd"

  template_file_id = proxmox_virtual_environment_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "BC:24:11:41:A8:4A"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = onepassword_item.lxc_access.password
  unprivileged = true

  started       = true
  start_on_boot = false

  tags = ["automation", "lxc"]
}

module "rabbit_pbs_01_psp_ddlns_net_lxc" {
  source = "../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname        = "pbs-01-psp.ddlns.net"
  vmid            = 802
  node_name       = "rabbit-01-psp"
  description     = "pbs-01-psp.ddlns.net"

  cpu_cores       = 4
  memory          = 4096
  swap            = 0
  disk_size       = 30
  disk_datastore  = "data-ssd"

  template_file_id = proxmox_virtual_environment_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "debian"

  network_bridge         = "vmbr0"
  network_mac_address    = "BC:24:11:D1:13:50"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "192.168.122.101/24"
    ipv4_gateway = "192.168.122.1"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  tags = ["backup"]
}

module "rabbit_squid_ddlns_net_lxc" {
  source = "../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname        = "squid.ddlns.net"
  vmid            = 801
  node_name       = "rabbit-01-psp"
  description     = "squid.ddlns.net"

  cpu_cores       = 2
  memory          = 2048
  swap            = 0
  disk_size       = 20
  disk_datastore  = "data-ssd"

  template_file_id = proxmox_virtual_environment_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr2"
  network_mac_address    = "BC:24:11:E3:04:A9"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "10.10.40.100/24"
    ipv4_gateway = "10.10.40.1"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  tags = ["automation", "container", "lxc", "proxy", "ubuntu"]
}

module "rabbit_rtmp1_ddlns_net_lxc" {
  source = "../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.rabbit
  }

  hostname        = "rtmp1.ddlns.net"
  vmid            = 803
  node_name       = "rabbit-01-psp"
  description     = "rtmp1.ddlns.net"

  cpu_cores       = 8
  memory          = 8192
  swap            = 0
  disk_size       = 30
  disk_datastore  = "data-ssd2"

  template_file_id = proxmox_virtual_environment_download_file.rabbit_ubuntu_24_04_lxc.id
  os_type          = "ubuntu"

  network_bridge         = "vmbr1"
  network_mac_address    = "62:F1:59:86:4E:CC"
  network_interface_name = "eth0"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]
  password     = onepassword_item.lxc_access.password
  unprivileged = true

  started       = false
  start_on_boot = false

  tags = ["automation", "lxc"]
}

module "rabbit_web1_ddlns_net_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "web1.ddlns.net"
  vmid        = 501
  node_name   = "rabbit-01-psp"
  description = "web1.ddlns.net"

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 4096

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "virtio0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide2"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "virtio1"
    }
  ]

  network_bridge = "vmbr1"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = false
  start_on_boot = true

  tags = ["automation", "ubuntu", "web1"]
}

module "rabbit_rtmp1_ddlns_net_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "rtmp1.ddlns.net"
  vmid        = 601
  node_name   = "rabbit-01-psp"
  description = "rtmp1.ddlns.net"

  cpu_cores = 8
  cpu_type  = "host"
  memory    = 8192

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "virtio0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide2"
    }
  ]

  network_bridge = "vmbr1"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = false
  start_on_boot = true

  tags = ["automation", "rtmp1", "ubuntu"]
}

module "rabbit_kubenuc_w4_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "kubenuc-w4"
  vmid        = 4002
  node_name   = "rabbit-01-psp"
  description = "kubenuc-w4"

  cpu_cores = 8
  cpu_type  = "host"
  memory    = 16384

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi1"
    }
  ]

  network_bridge = "vmbr2"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm"]
}

module "rabbit_debiandesktop_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "DebianDesktop"
  vmid        = 101
  node_name   = "rabbit-01-psp"
  description = "DebianDesktop"

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 4096

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    }
  ]

  network_bridge = "vmbr1"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = false
  start_on_boot = true

  tags = ["automation", "vm"]
}

module "rabbit_r_3cx_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "3cx"
  vmid        = 105
  node_name   = "rabbit-01-psp"
  description = "3cx"

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 4096

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide2"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    }
  ]

  network_bridge = "vmbr1"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["pbx"]
}

module "rabbit_squid_ddlns_net_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "squid.ddlns.net"
  vmid        = 104
  node_name   = "rabbit-01-psp"
  description = "squid.ddlns.net"

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 2048

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    }
  ]

  network_bridge = "vmbr2"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["proxy"]
}

module "rabbit_kubenuc_m4_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "kubenuc-m4"
  vmid        = 4003
  node_name   = "rabbit-01-psp"
  description = "kubenuc-m4"

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 6144

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    }
  ]

  network_bridge = "vmbr2"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm"]
}

module "rabbit_mail2_bioadventures_eu_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "mail2.bioadventures.eu"
  vmid        = 1001
  node_name   = "rabbit-01-psp"
  description = "mail2.bioadventures.eu"

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 6140

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi1"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide2"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    }
  ]

  network_bridge = "vmbr1"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm"]
}

module "rabbit_sophosxg_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "SophosXG"
  vmid        = 100
  node_name   = "rabbit-01-psp"
  description = "SophosXG"

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 6144

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "virtio0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide2"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "virtio1"
    }
  ]

  network_bridge = "vmbr4"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["firewall"]
}

module "rabbit_docker_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "docker"
  vmid        = 103
  node_name   = "rabbit-01-psp"
  description = "docker"

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 8192

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide2"
    }
  ]

  network_bridge = "vmbr1"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = false
  start_on_boot = true

  tags = ["automation", "vm"]
}

module "rabbit_runner_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "runner"
  vmid        = 5000
  node_name   = "rabbit-01-psp"
  description = "runner"

  cpu_cores = 12
  cpu_type  = "host"
  memory    = 12288

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    }
  ]

  network_bridge = "vmbr1"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["github"]
}

module "rabbit_k3s_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "k3s"
  vmid        = 102
  node_name   = "rabbit-01-psp"
  description = "k3s"

  cpu_cores = 8
  cpu_type  = "host"
  memory    = 16192

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "ide2"
    }
  ]

  network_bridge = "vmbr1"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm"]
}

module "rabbit_kubenuc_m3_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "kubenuc-m3"
  vmid        = 4000
  node_name   = "rabbit-01-psp"
  description = "kubenuc-m3"

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 6144

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi1"
    }
  ]

  network_bridge = "vmbr2"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm"]
}

module "rabbit_kubenuc_w3_vm" {
  source = "../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.rabbit
  }

  name        = "kubenuc-w3"
  vmid        = 4001
  node_name   = "rabbit-01-psp"
  description = "kubenuc-w3"

  cpu_cores = 8
  cpu_type  = "host"
  memory    = 16384

  disks = [
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi3"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi0"
    },
    {
      datastore_id = "local-lvm"
      size         = 32
      interface    = "scsi2"
    }
  ]

  network_bridge = "vmbr2"
  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm"]
}
