---
apiVersion: v1
kind: Secret
metadata:
  name: film-tv-secret
  namespace: film-tv
type: Opaque
stringData:
  radarr_url: "http://radarr:7878"
  radarr_api_key: "test"
  lidarr_url: "http://lidarr:8686"
  lidarr_api_key: "test"
  sonarr_url: "http://sonarr:8989"
  sonarr_api_key: "test"
