apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - ingress.yml
  - networkpolicy.yml

configMapGenerator:
  - name: proxmox-selfreg-shim-code
    namespace: proxmox-selfreg-shim
    files:
      - shim-main.py
