---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sso-secrets
  namespace: flux-system
spec:
  targetNamespace: sso
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/sso/secrets
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sso
  namespace: flux-system
spec:
  targetNamespace: sso
  path: ./clusters/kubenuc/apps/sso/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 15m
