# TMP namespace creation
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: 1p-operator
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/harbor/secrets
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  dependsOn:
    - name: openebs
    - name: harbor-secrets
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/harbor/manifests
  prune: true
  patches:
    - target:
        kind: HelmRelease
        name: harbor
      patch: |
        - op: replace
          path: /spec/values/core/replicas
          value: 1
        - op: replace
          path: /spec/values/portal/replicas
          value: 1
        - op: replace
          path: /spec/values/persistence/persistentVolumeClaim/registry/size
          value: 1Gi
        - op: remove
          path: /spec/values/portal/topologySpreadConstraints
        - op: remove
          path: /spec/values/core/topologySpreadConstraints
    - target:
        kind: HelmRelease
        name: redis
      patch: |
        - op: remove
          path: /spec/values/master/topologySpreadConstraints
        - op: remove
          path: /spec/values/replica
    - target:
        kind: CronJob
        name: harbor-db-backup
      patch: |
        apiVersion: batch/v1
        kind: CronJob
        metadata:
          name: harbor-db-backup
        $patch: delete
