apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql-nuc-cluster
  namespace: databases
spec:
  teamId: "ddlns"
  volume:
    size: 10Gi
    storageClass: "longhorn"
  numberOfInstances: 3
  postgresql:
    version: "15"
    parameters:
      max_connections: "300"
  resources:
    limits:
      cpu: "4"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 1Gi
