apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql-nuc-cluster
  namespace: databases
spec:
  additionalVolumes:
  - mountPath: /tmp/queries.yaml
    name: customqueries
    subPath: queries.yaml
    targetContainers:
    - exporter
    volumeSource:
      configMap:
        name: postgresql-exporter-server-queries
  teamId: "ddlns"
  volume:
    size: 10Gi
    storageClass: "longhorn"
  numberOfInstances: 3
  podAnnotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
    target-version: "16"
  postgresql:
    version: "16"
    parameters:
      max_connections: "300"
  resources:
    limits:
      cpu: "4"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 1Gi
  sidecars:
  - env:
    - name: DATA_SOURCE_URI
      value: localhost:5432/postgres?sslmode=disable
    - name: DATA_SOURCE_USER
      value: "postgres"
    - name: DATA_SOURCE_PASS
      valueFrom:
        secretKeyRef:
          name: "postgresql-exporter-secrets"
          key: PGPASSWORD
    - name: PG_EXPORTER_EXTEND_QUERY_PATH
      value: /tmp/queries.yaml
    image: quay.io/sysdig/postgresql-exporter:v0.11.6
    name: exporter
    ports:
    - containerPort: 9187
      name: exporter
      protocol: TCP
    resources:
      limits:
        cpu: 250m
        memory: 256M
      requests:
        cpu: 100m
        memory: 200M
