---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: unifi
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: unifi-poller
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    env:
      TZ: Europe/Rome
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: unifi-poller-secret
        subPath:
          - path: up.conf
            mountPath: /etc/unifi-poller/up.conf
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9130"
      prometheus.io/path: "/metrics"
