---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1password-secrets
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/k3s-prod-test/1password-secrets/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
