---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: operator
      version: "5.0.11"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      host: console.minio.ddlns.net
      path: /
      pathType: Prefix
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: nextcloud-fastnetserv
spec:
  dependsOn:
    - name: minio-operator
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: tenant
      version: "5.0.11"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    tenant:
      name: s3-nx
    pools:
      - servers: 3
        name: pool-0
        volumesPerServer: 3
        size: 10Gi
        storageClassName: longhorn
    ingress:
      api:
        enabled: true
        ingressClassName: "nginx"
        host: nx.minio.ddlns.net
        path: /
        pathType: Prefix
      console:
        enabled: true
        ingressClassName: "nginx"
        host: nx.minio-console.ddlns.net
        path: /
        pathType: Prefix
