---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: sysdig
      version: 1.15.23
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    clusterName: ranchernuc
    nodeAnalyzer:
      apiEndpoint: eu1.app.sysdig.com
      imageAnalyzer:
        containerdSocketPath: unix:///run/k3s/containerd/containerd.sock
    sysdig:
      existingAccessKeySecret: sysdig-agent
      settings:
        collector: ingest-eu1.app.sysdig.com
        collector_port: 6443
        app_checks:
          - name: nginx
            enabled: false
          - name: apache
            enabled: false
          - name: redis
            enabled: false
        cri:
          socket_path: /run/k3s/containerd/containerd.sock
        log:
          file_priority: warning
          console_priority: info
          event_priority: warning
        prometheus:
          enabled: true
          prom_service_discovery: true
        jmx:
          enabled: false
