apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage-s3
  namespace: flux-system
spec:
  dependsOn:
    - name: openebs
  targetNamespace: nextcloud-fastnetserv
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/s3/manifests
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: garage-s3
      namespace: nextcloud-fastnetserv
