---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-vars
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/k3s-rabbit/vars
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
