---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: operator
      version: "6.0.2"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    console:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        host: console.minio.ddlns.net
        path: /
        pathType: Prefix
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: nextcloud-fastnetserv
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: tenant
      version: "6.0.2"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    tenant:
      name: s3-nx
      pools:
        - servers: 3
          name: pool-0
          volumesPerServer: 4
          size: 10Gi
          storageClassName: longhorn
      metrics:
        enabled: true
        port: 9000
        protocol: https
    ingress:
      api:
        enabled: true
        ingressClassName: "nginx"
        host: nx.minio.ddlns.net
        path: /
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        tls:
          - secretName: api-minio-tls
            hosts:
              - nx.minio.ddlns.net
      console:
        enabled: true
        ingressClassName: "nginx"
        host: nx.minio-console.ddlns.net
        path: /
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        tls:
          - secretName: console-minio-tls
            hosts:
              - nx.minio-console.ddlns.net
