#ENC[AES256_GCM,data:1Ytb7xjgsqWZn6K6oe+sald3RBT6B+NDAtfDf2Fo1FEBru2DxyJKR7MC8n4seylmTUULEsupIlY1,iv:CKZYCOX6hZDy5HoDI0TkeRT4A7tfoYIREWpEwqpcJZg=,tag:kZrE6yazEtn+tDuOVd8WkQ==,type:comment]
#ENC[AES256_GCM,data:KB8lVP7FfU8F3onVWrvEGSjIMnt6Gs56F2V9Wud3g/pDBrynvO9Kv1O1hMktqPFarJQyVN76AeGHj0GoJD5YqF3Tnrk43s98UUwHJeVzWEH7tK7B,iv:kVz9uWbhG0ysCyLAMgzoAbhOIgfrSSqsLwjCPtu3Ltk=,tag:oHfpfUgLfu98OMn3mcSZWg==,type:comment]
#
#ENC[AES256_GCM,data:43Uh3t7nzkP2Oiw8u5j0KsUze2uevCA7fatTZ8ogW7Z3u1Uay2ADQQ==,iv:BtM2j65doPT6VqzXPTY605XPJ9g4JRaNHgkH0jtjcjM=,tag:vejExq0Wxj2Up6wetfMrpw==,type:comment]
#ENC[AES256_GCM,data:KeeLAz2ZOjg6SM3gG9Kl42dWm+Hn4XQz79GC0mo/ufMehw==,iv:ogsjtES/FmfeTr8iJkNX01XsDsDmFh0G2WF8Ib5zQDI=,tag:h88hrFTwJn41mwIC8jPtVg==,type:comment]
#ENC[AES256_GCM,data:oHZ1fZf54AENAXA6dFVqDbt4n+GnvF16oJLyGp3fILikRx9TokABFSXCmw==,iv:qGuXDD6br0RKI3jYl3NWV1ht8WtCTl7f+3j6LuBam1g=,tag:niVUz/xFUJ8z2WlsBKEQFQ==,type:comment]
#ENC[AES256_GCM,data:Ajo7IvKHHqnRAZYDxB5GMeFvB3oQFNkmkYdFlwjd,iv:5y1AZso8wAv0WTZGgRrhm5o3YMr0IWGiFntircs7ebI=,tag:Cw9H2/uBbo8MuQfslj8baA==,type:comment]
#ENC[AES256_GCM,data:JOG1Jmz0qGsHrwiTPvfgAM2vbsTvrKiRDItbM4AgQgpVGwrwDI6f3sI7b/JScic=,iv:0utjs3rZe+YtA9SvWyFWEFGJ+A1tGFs/ZabneBUDV60=,tag:KU0DPy2vLpaqVeJN/Sdk9w==,type:comment]
#ENC[AES256_GCM,data:4iDhHN6W4agobLMi9oG/y252jOK2CqjfeUxyickfOgH0WcqQJsL9zg==,iv:wjXMjGmV1BE+o3Yu5ykIW17pgrCjWEvK7Wcn1/EVhBM=,tag:RUT3LXvIeyz2ibWlYGXypw==,type:comment]
#ENC[AES256_GCM,data:nndKzfMAXnQJJrszLigMc0phZkC+2FYhYb+OxeQL1Om8A/Ha5FKmZFsdMWEU8TH6gRycOd3q/zQKqBnHQNwTYSMq2w==,iv:VJHBdiTeIqSqHJw5MeQRAOJwj4vY+lzXERqv//s9MTk=,tag:ThJksQ89ZSFtzFC5mhtNuw==,type:comment]
#ENC[AES256_GCM,data:598RoMntegM+kxT0RIT++75lADknL3ZGMx5XTs+HNVy1Ve6+2GDOvsPcfMim0vcCItwIryMLfYCMsA==,iv:gKYmyDViZkOZu2H283YgyfxjXNde02nHKKQ18+N2jm8=,tag:v4Ro4eaFzYHskSbw9W1wJg==,type:comment]
apiVersion: ENC[AES256_GCM,data:/ts=,iv:OQcnCgAig843hPzSj7ftj+yOB+oegG4hxvLdFuDQuEQ=,tag:Rv5N9ENEiM6SfIpk4ESBpw==,type:str]
kind: ENC[AES256_GCM,data:3MFKOpIp,iv:oh3YkHlb43UJNkU3GZsBCwnepiUZ/aRZxhWVCAUO5HQ=,tag:RAiTy0AN/32gBZvB8alVrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o6RZ3QpQ0YBfMhqR,iv:jcgpS5VL5yr+R7O26KpguXpfMNMZIWYubqpFb8NkzxQ=,tag:hKpM5FuaMMMPMUcGPsedYg==,type:str]
    namespace: ENC[AES256_GCM,data:4GpjEfOizwHzN1s=,iv:K1SXhyZ5RsyqBNwjdkIyxUMqkoCBqzAsGdCILlCNass=,tag:kOmrjh5OmWwsR7YzCDHRRQ==,type:str]
stringData:
    SEMAPHORE_HOST: ENC[AES256_GCM,data:3LdqRpP7RtsIBvqQwbUCr6hI1PtQVHe7Qw==,iv:lXoTN06LNoHYfVxIyqLS40g72Mrhzpf4LsBbYYrUITU=,tag:/ilAQ8g62Cg3g+TwfsqFpA==,type:str]
    GRAFANA_PROMETHEUS_URL: ENC[AES256_GCM,data:iy2AO7c494KWTTh0FyfiCGm5LoRUiXa3PIdPzOuYJxa2UO2EfrL3HdxT7Nj9MUwCNW2cYdL/jXD8TKn62j4YUQXXI7sWyQ==,iv:zljWumiV4mgd5knukeZF+VuTDhxAITaddm0SyeDPJvQ=,tag:zCb8/GCHajxcBGfjbfE+GQ==,type:str]
    GRAFANA_LOKI_URL: ENC[AES256_GCM,data:sbYb5gMTs4Kaowkhtsk4MeYfqZtQQj+NcJmYmnr8YSMT88oHqfDQunmNCcq2iTyNhms=,iv:C9g16SFTsUW4J2U5MHf9jq9mqO6MeCuwQP02mix/bkg=,tag:47acXMgvU35nmP9eT1HBwA==,type:str]
    GRAFANA_LOKI_HOST: ENC[AES256_GCM,data:CzL+48r3TM3Xo+Mzk8Ni3h9v8v57RhXvqsh2ugY54x3v,iv:PbvcYyfpiCzdHYZGuXd9QVRHWMv1qEPUUJqlLBw5kfo=,tag:+QseyvouNNOs2+/zQMAILQ==,type:str]
    AWX_HOST: ENC[AES256_GCM,data:Qx0yjzrc46w4VeH0jifX6/FAdTboAGA=,iv:2EUjIBhCYHuIscJ4Kr8v48yPxyFyX6yRPbIhua2TR2k=,tag:reihUTDIC/ZUIgutHnem1w==,type:str]
    TELEPORT_HOST: ENC[AES256_GCM,data:MQXemWHJv7bhb18AnoLDXiiI,iv:A7JGe2U1pdqzd6G+BkePSbe83l3Apt4ZYWlEFs5Xp1U=,tag:9e21va8upvhsxkMbkJ/Dyg==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:ud/jFrVAd600,iv:Xkbzfy03QzU6DElTfl0GNh8Vy50SpfTtBnwzcYFZtEk=,tag:W7Bjgv2sI+xoB9/dQGVv4A==,type:str]
    FASTNETSERV_DOMAIN: ENC[AES256_GCM,data:cOrqlHvCLoz+MXEslg3I,iv:ghz41K1V016owlYmQpENSpDCk6q66ciwGOEQJ5AZul4=,tag:acmS+ENhGgOBmvoThHb3PQ==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:VkjrB4GJeFiUWzTETfS+f4lqWxfhHFulDt24lXpGZUCM,iv:+xqcU+gv+TdqQVIaxaCvhwy6CXRStH3i3xzXzQqsNSc=,tag:hK1sT8O+4StcjKEq1Voejg==,type:str]
    CLOUDFLARE_TUNNEL_TARGET: ENC[AES256_GCM,data:WrjKIw4kTL5NWLz+hJ0NOiaz4fQ9YOJm2mGS+RRSKDLXrDmlpliNGe4VZAdVDzDRGZ5yWL0=,iv:K6b5E9dimvJEY//RX95hBurkYylzcH+b3FtpTbRuJCs=,tag:FlSVfoUupJs6yQUbm6HBIA==,type:str]
    FLUX_WEBHOOK_HOST: ENC[AES256_GCM,data:nVF+DR3OuG2k0RvvJE4hZvoCBtU5F6EPaJ98WcQLAQ==,iv:O9vjZJ/F99bUXU2oMT6aNm2KDCfzCUhPF58EZyQbgKY=,tag:zbM2CZ/MG5gjI3kn5g01sA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaGZmcit2ak5oZzI5VDRQ
            Rytha0M1MklXV1FYTjZYZ000UnZaSkQvekF3CmZQQUVYb2hyRXBzSGsvSkdlcjl2
            bzBVYmhBR09nNDA1ZVkyUS9EZ2xlMlkKLS0tIDhmQU9IOUpYUkFWWWxER2tXekRV
            YmpPSllRZGJnTnhmZjlqdnRZUnpHd00KDDeWN4NLDKtXT0dPFE0phvXEl2koJ+I4
            d47T9O/Yuty1XD9I7Rd1rxsbzIFFF/VzJwS98n+HaMQHwB7HR/CE3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10zqzjdvku9q2qpq34pqjvss9jarc86wyqxe07x6f0qd8c2w9tvss03awl3
    lastmodified: "2026-08-09T08:01:47Z"
    mac: ENC[AES256_GCM,data:5c4Ty/AIR6lbLAm/kFc4quTLJrLNxOoBDs2j7cT5g+EZzSstYzLZvzDwX8NUe2NC/hcFpU2V9ejvMz8I64kAnlr8FUjZuxKMANTzHSXMNcHRj633BRb3I4qaImnf5v9qk8rqw5zQ4jYcGqK7WRUL2gCig6MxHJlC0aGxbcTFFMQ=,iv:CswrmNKWN7efw7xSnWbYQUEYjjk5WXmZ9+v1DYKPzxY=,tag:0AbTQ+XDNpHHoRaRT25NbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
