---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ascender-chart
  namespace: flux-system
spec:
  interval: 1h
  url: https://ctrliq.github.io/ascender-operator/
  timeout: 3m
