apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - falcosecurity.yml
  - grafana.yml
  - jetstack.yml
  - prometheus-community.yml
  - semaphoreui.yml
  - teleport.yml
