apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: awx-test-admin-secret
  namespace: awx-test
spec:
  itemPath: "vaults/k8s_secrets/items/awx_test_admin"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: custom-awx-test-secret-key
  namespace: awx-test
spec:
  itemPath: "vaults/k8s_secrets/items/awx_test_secret_key"
