apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: 1password
stringData:
    token: ENC[AES256_GCM,data:lcbgtkIAmivRzeUYRIx80k1wDJkEXsKPL+HoaiA2R4uMET5vgtbe,iv:hO+56EpSilHrvY9YkrUC4P2RNnLPp4EFN7HBYY8TNNg=,tag:4YGnNt5yQHkTzyy2JH2q/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRG5jVGxsMUVzcllNRW9Y
            TS9DaUxVdTRXN09pNTJtSWhQemluVmVPRUZrCkRvczJnWGNtRzQ3cHhXUVFDN003
            Y05VcHF3ZmxrVnFLVWp1MGJUY3JxV0UKLS0tIFhiOUk5SkxrREFuWDcwZlBWb051
            MWRNU0s3d1VIUDVVYmxjZDFUZy9RQzgKmiQy5cck2kTDaweA7HOuFvQAxLCSim2K
            Tz+QXWH6e84A8a4xj981pHhsf7yQQyvJb4cdCfgT18kwR7jEzRPJgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12tmgn4lmzp3u3ruzhzyghc7qzx3zk8nc0p44kryq88dfg72vufrsc4d0tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T17:42:25Z"
    mac: ENC[AES256_GCM,data:1vVFRSfoM/17wGt7tqPWeBzroFnOBGgEtFUXE46myfoAZ0C/17AAnG51M9w6cN+uBvA1E0LcixQchpuEY3dVQ2CKgtrvIcm7TYxAKrQCZpH4M+vpM0z9oszjrXIavsNE2hxto5U9BY1f+Xka8cSZ02LGlUfb45wamoeqyxikZHo=,iv:b3BCv0ceP0KViI8Fru3zh5VUUj1xXQE85KjdVwb/opI=,tag:+XeWy/DHSot06q4Pgb/Lsw==,type:str]
    version: 3.13.3
