apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: 1password
stringData:
    token: ENC[AES256_GCM,data:L9ezqKl1qgRhBfJPEaM6lzY0rnc8IkpIaxU78WL8+Xg8VHczll61cydpq6UXMZ5gyKsYsgFbp73XgpEWEhFFBSvXM0dvjFQLrXHMX9Tt2zyfSuJHMJsKETaFodLnFDMgV7v2JS/XBuXQeyCjxVyIIxHinyiVWxld5te1wI/dlllWhzZnWQvSGLkNwyrG32utfJC8tcpuv7KS0I6nZok9bU52YlqkCey4/GlP6ucgCf2OZ+RfTzBlm5k/pP23VMJ+5H2NUQWCsP2dx4Oiximcn2lE7DygZZ6KGAOnDW8rm/OZxPI3A4mIJ1w2sXXzGt1548ir4pvezfRZF20Q5+PoH5SWb4+ljagcexJ5LkP9S39BT10rPJi0qOauLbm5tODT0w0M42l4anbYXS27fZTtRcoy3yqnUBtOp4dznS3i6XflgmuzDDmdVKjwTu1d/mnb9+NtX0+U/Tdi7O5Ttwl16SguKE+a7oO2FmRoKFi6r0oB/qOapbaavXH53q6ocDItmpHGg9Gj0aFZq6C3TDdEqDWm+mHkEuIfUcfyKj0kk3qbbdIPR4nEe1mDIgqy7UBThOrSL23wztrY2ATLLzMFGR4+E4gdzTxRVUIDVO7MBiCRzbDl71MRxGUhbVVJ7Tq2LE4RqO6bS1ViltB21hV/B43THlJC7Xxw0MGajv/l3oenv3dpJIOKBG6bK+dJV/oEpGDZci/vfPZznMDiRo45RtnfCK6UqE+bpn79k2/dq+yKGQ4b7IXiCChasMkLswiks8krwLyoOCXZiHx3GxhoNXMA7QZtfnHGp+G8tuRWuEq7UonVxzbRPktmfuFtysKiIlvr1sAHEPoxgnVAZLFEgWDY,iv:DvHUdkmyinzQGLIXww1ASTIViRzscRUCa/fCMU2Znmc=,tag:o4BgIgKd9FLRfpxaJ+NeJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Wngwcmhud2dNVlc0OWRL
            dExRWFcwVWZZc0JlSHdFa05GU3VLUEdZa1JBCnE0MWNYNmVEZnUwZGJ0MGtnU1ZX
            YzFQUXhoczR4OTlzL28vZ29BVzJkUVkKLS0tIHAySkhMREhmNkUxYVdoNUI2K01m
            b3gyS1U5WEpJUzVtUnRicXVGd2FCWkUKjYg4IcPGHATrjKUQUTXuq1rUrR2Rl3AO
            x+BXKRSV09j4QQ6ukHfZQ+l3QSZMoCFNEqbCEytoeHZUBZL+fMVemw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12tmgn4lmzp3u3ruzhzyghc7qzx3zk8nc0p44kryq88dfg72vufrsc4d0tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T18:29:07Z"
    mac: ENC[AES256_GCM,data:OkM3WSz3sZq4tp72eGZHlqQXXpLtL5SCqoxPkIVKcz0MNmW6YfmHfK0RNTH7Zqhev9z++3MidFNpI4Dj5E+NCb9Am7uXwtSZroQMvE7km/FWjEiE61wRL2V9RFuVt5mBihPqFkefAqyQDEsAL/C5ag7qj9B6pJaruwv6CTQrGlY=,iv:GM7mte9MliSmfjzJwK5uvp9hdSPla7wJ8HSqPrtyr5M=,tag:dIsBa6u67s4XlLrVQhXcrQ==,type:str]
    version: 3.13.3
