apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: 1password
stringData:
    token: ENC[AES256_GCM,data:cTG5FAbLoa3Iq8RnrY03bX43aYBi9HmBGA0ahNW/r3Ji37MZqEff7YtxHxlnvA/rVHmI4+bCNYoswboKSx+VuD/zufpO9CGIz9py6eAGK1ciqRtVmRg82X4mU3f0BUSExT6f2Fhs/jo2t46ogKsMi3ECsYnQMvtn6P2tBH/OMLJqv3UbQvtQ9+erFMuEhMve+uZlf9OtUJACvq8AN/x1h7B1tvCpuMBnD5W0AxQohb8bjc5XURiIwznfGsOXaMmn7u/MTqe8j79LMyTbxkJt3D1I2FG1FT5PUMdNEFb/bqjLPlEK8Vevg0eFJrRH43x/Nn/AAqeVaUMhVF7e/gX7JExoU9VW8gm1FebMlcJzFNyDWhSGTnpbbXTy0Rgaz29dLDehvI6JUm9DLZ9r97kJ6NaZPwSVtuOGK/5Izfsv9eUgpxKGbkhmiMsrAll79cwZ1tyw5FB0F+D0w0eYhodIdNHWWCp2ajjUyapPOaRlJavM8fa5rqa6YKt7h52dj4Oos+N5fEcRhoPwThrVKZwv3tIUN0OpI30nPZ6fLMbKJX6UVqvwef1qrJygEQHVspcgmK+F6YcGoy4TzlEnM5ZoKVUst7S9Uw69mKPrCHaTV9mnQn5vyl2Rjio/RY61OxIjCrYNy2GCZByM4HBKQSGdpyh7u8jQL0rY/vIKGR0glRGg68eD9tsfBGTeUHtTOpdVY1OAjIPIXtP6tT/bmozEA4LmhgWyGc9jOzlS7/67T1tGtuPwM34jnYdZ/EMfXVbOQALJcPrVInM36xfJ4DehOvkjKeWWkCwDfUGPvNjZ20RTUvDnEo/nsdcMnTs8hph6mzlB9B0Jl6cGTtsmKefwmA+M,iv:VGaCFqgAQh5oPWuly8zvaPr6VCVLoXQ7tqHYvX/Opuo=,tag:3ayxvSHI8eCUTH4+cmXcKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N3FsNnRnNUtlSHk5cEpk
            Wk50UndsS3ZrQ1RPOTFjbW1La1FrUW9TS0JJCmtLdm5rcEt3YmpyWGJBUnYrWjgx
            Zk1HV0RsaEJBbmh6WlA3V0I1L1VyczQKLS0tIEtLUmxYSTZRYjhGc1lxMlhmNHRO
            ZFBTeVZVZWhhdFp3UHFuRG5WMTltSTQKbjuggJVgNvGNQL+Gz7iighFkiU3kEUIm
            VVYjk0VR1ceK1S/zWTADOrJ2DDwVyxTERyjPNNX/R6h7hSONfUxLUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12tmgn4lmzp3u3ruzhzyghc7qzx3zk8nc0p44kryq88dfg72vufrsc4d0tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T17:47:46Z"
    mac: ENC[AES256_GCM,data:bChOYZDXxxNC4k0zscBsse+mPZhe3LotEvVpf4+FKnqKfBCDRLU3beBIoa+U8WlsNdK4AnOnyI+CPMVX1fb6GdPE2Afm3bfPunepfaCzphI9pGwBWWnKfsIjCAeVJWDTI5LkLd/30Swyt84mqk7te2ij0hELCV5sOsS2qA5jv4Y=,iv:tMLB2Ov7jdhfrGpnwyM52CuBxlA7k4xNUuFKw1ArG2w=,tag:/nlby45HtHyQX2SJp8sqjw==,type:str]
    version: 3.13.3
