apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: 1password
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:wtIJBAWe9Osrv48xz9IUZCZ1EjhAv15Dtylg1AuOj12XSZ749lgm0t65/SZ5OiQ66vU9hbP6Ral++lGP2FJq50e4WJdiB8koI5ybORuYyBGpq/HlpfMOnLI+1fIDa3z21L9+Ni5eHXLF+Z2eVZ7suU/7aNkbnV5esbyYWpTEKlOAHNqT8GIOTf+MSSfgpdZYCmcsGCwDsgsb0xpUGG8x3wyi3JsP/lHfiCAIQm5ekVZHpVQotgva8A3rvl9HsG+VOXHla4KblgpPhNqRCtxEst61pPuEqoJGS4yoQgNiuqmiFV89s+/SwcN8hRm453LsuSI9AjJgtogGrfPdvL6AIOPPPCukx1KXEFWe8dHKC/Q2CRHfScLihw2VtTPp0lxJTfDYKD3NITXwivtRwxdRvYZNcV/FNFEiOfT29Bw8OoeOTcLJ7qVOw2HP+D5RIXptroWlxHJw43cPjgFvTSi5NeKWcih9hL2XyITLNZWbxeIUKF/BNy3A169GwmiC8P6LQJ6IeCcMXEpo0PCgj29v8NWfjBoKfbQsM4dF5HzwJ3+SNUTbcVXsSlaBH9qdNpnF+Ld/sqKUZuH+3i18ItvJ8OlHoy1aX/GI99q6ZYjcOK9FiFpqiakR+vY376Q0I0F5MYxBfJZAk963J64RRpU0fFZv5sklsORpcNF/gEUvE8gXqH1gs/u11sdm8hkxyETiKSCwzEWxfr9/qADHhGWEd+v9Th6t2IFGyTMUDtMAXuIV6Y0Kkb0nxZ/ZePfOOUavN3vbUea4CLPPrjxp4JMnbyPl28bZzHSu+lnLBjwcNSQX8DO/HI5jafn8hE6Y7E5X2aDI16Lw/cf6qX2RQ/bvJx6vcH2b3XnnabMK7BL6rVU1btVPw/rhzwkB1Nk15Bzi6IEVQb1Fy+Vy5y2EnBGEAACk71dOlIM9Vehv56fIIDP36cpEE8+GgEL3P5uRkUIO/MDOgVYoTdLPMvlUA3wF70GxRsuLashVs4a4eWxYAG20GHmxAuFH9xZ7RRtAgyAjnDdg7UUVNwRLhexKTuKoJRpsNxSLuBu9O6FhZqVib65dmC7Tey6TvnkTTgX7StEdU8saYPgF586mc6/JbTsD5PLeWqCJXnzYvvf/CeZKQIqTZGfMMTUPelV92lrVgyrwaoBx+iZmwGc3Eybz7HziY4NSF1huI5o8SeQpAi+XjfVQqeRVgX8rd2+eBrx+Nk71OLWO7cunoYVrdaA7XpQq0FpA5a0JyCnkLHbUcg5pqYgc/whK1gdBXiQ3fDggyEp0mF/1d3qij4+QRAADuMM+1e7O+Da5cWePFPUK8LIxl80Nk9HR7Y4M1iw6iL3MXiz+e2TZPtc87LcjPNGW6tVpourk0W+L46qtrvrK0PhRvsSzz6GlaoWqY45hSkVRf2peJxazekuvYrRxphcV+6VHhJhjNMGA4bLNQCOAEMao2g==,iv:EQP/hEFnQ9961cRNJniQ1Dv0pIO/dKFgNxfrxik07ak=,tag:HbhdxP44Ltyqix4os10QkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVEJKNFUzZ0RNR1VhOFZj
            ZitjYm1IZTU0eDZ2aSt2ejJoU0dHZFRTeFgwCkpZdVdqS2xrZWN0WDlPZXR0QkhP
            YXB3dzYxd2d6UmlMZlNZRisvNVRMdUUKLS0tIEZsc2pTWGhJV1F6dDIrRWZwNnZy
            ajNjUUNMOEoyZEVBaGRybUc2TmJaQlUKDMXB1yG6SyoQDOdYJnh6ulbS5809H/kK
            ijN4J3K6+47b5c5lbHat6Re3b51d4lTtsLThwlR+2Pe6jv4zf94YfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12tmgn4lmzp3u3ruzhzyghc7qzx3zk8nc0p44kryq88dfg72vufrsc4d0tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T18:36:11Z"
    mac: ENC[AES256_GCM,data:fElpMnCU66g771vlqbhJHRSKMaDuc4HTyDnXzslqMaRkQH+sCYkupEu37medZ7oJHOQXL2vTKptYvrDAgcUxwVsu2jjpbIJF42pNI39G/oU1gVQFMpcUb5WDhTDqd0KBNW+BstFZltYW0j7EoCX00JG5mrDjzigsC+OB9qcl1kE=,iv:UlrcyH6rD0GPDn2OsAMyrBNKXG8pBBnuZIGVARHq9ok=,tag:taZ0zjzMrlrMNu1ZdKx7Kg==,type:str]
    version: 3.13.3
