apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: 1password
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:fshqyoaLJ/dZk7MVZnr4NzvLgzpD4T72dQTLTB7Km0kKTgycvqHgVFclQ1a1ItwIleGYY91n+bQ=,iv:LJSk6x/FqtrKPwiRs465uXeRSLypTcJh5XLwDJmtoNw=,tag:12R5uUHIZSTyLTP963o93g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0czdKUFBjWllxOXdZZ21j
            TDJVUGQ4Q0E5cmVtZDlLZzNCUGc4V05aVEZJCnFUVWJTTWVmNi9DU2xuVVZ6N0U5
            eUREa1lWSGxMaWFPaFVXVnh4T1hCWWsKLS0tIFNBNE56QTRPV1NXQ0tSNTF5OWNh
            WUNCZ0JkVzhSNnloNnhMeW5zKzlwcWcKs7TOqqo1a8a/2atWIjhm/KK6fKPkO2Q1
            fII5EqucEeT2DGuAZyokjZ49aTZXT1pZojOz1Oz8rQACUCGOPk5ozA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12tmgn4lmzp3u3ruzhzyghc7qzx3zk8nc0p44kryq88dfg72vufrsc4d0tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T17:42:25Z"
    mac: ENC[AES256_GCM,data:Iv0julXyLCJc8gZXkA+bwqzP4wsgRNOgjOWA5E4H43JV3FXEsI0zZSqC96CiMvyKQ3yWQREbcqwnH42zfkV1kUxgfisRHJ/qc4b1U9hzVkTSzNJHo7G2ZWFjkY1sWz4nR6wR6hPRyUcMqc4MeElELxQnN/ig7aNmQSk8r5J0+Mw=,iv:l089rW5fja1OIcqJyzEokqXe8gbVB9QXJu8M8VmDSUA=,tag:PsEI+LIZn5nDxU2IzNPF7w==,type:str]
    version: 3.13.3
