---
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
type: Opaque
stringData:
  access-key: test-access-key
---
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-rapid-response
  namespace: sysdig-agent
type: Opaque
stringData:
  rapid-response-password: testpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-agent-api
  namespace: sysdig-agent
type: Opaque
stringData:
  secure-api-token: test-api-token
