---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: harbor-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    externalURL: https://harbor.ddlns.net
    metrics:
      enabled: "true"
    # registry:
      # podAnnotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: "/metrics"
      #   prometheus.io/port: "8001"   
    notary:
      enabled: false
    expose: 
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/client-max-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts: 
          core: "harbor.ddlns.net"
      tls: 
        enabled: "true"
        secretName: "harbor-ingress-certificate"
      type: ingress
