---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql-secrets
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/postgresql/secrets
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/postgresql/manifests
  prune: false
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: postgres-operator
      namespace: databases
  patches:
    - target:
        kind: HelmRelease
        name: postgres-operator
      patch: |
        - op: replace
          path: /spec/values/configKubernetes/cluster_name_label
          value: "ranchernuc-test"
        - op: remove
          path: /spec/values/configKubernetes/pod_environment_secret
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql-db
  namespace: flux-system
spec:
  dependsOn:
    - name: postgresql
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/postgresql/db
  prune: false
  patches:
    - target:
        kind: postgresql
        name: postgresql-nuc-cluster
      patch: |
        - op: replace
          path: /spec/volume/size
          value: 4Gi
        - op: replace
          path: /spec/numberOfInstances
          value: 1
        - op: remove
          path: /spec/sidecars
        - op: remove
          path: /spec/additionalVolumes
