---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: distr-db-backup
  namespace: distr
spec:
  schedule: "0 3 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          dnsConfig:
            options:
              - name: ndots
                value: "2"
          containers:
          - name: pgbackup
            image: ghcr.io/solectrus/postgres-s3-backup:17@sha256:3a5d281955fd6bcdbb97628979ab4df83243253e1f5ebe90b2db13b05d65eda5
            imagePullPolicy: IfNotPresent
            workingDir: /backup
            command: ["sh", "-c"]
            args:
              - cp /run.sh /env.sh /backup.sh /restore.sh /backup/ && exec sh run.sh
            env:
            - name: S3_REGION
              value: "eu-south-1"
            - name: PGDUMP_EXTRA_OPTS
              value: "--schema=public --blobs"
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: distr-db-backup
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: distr-db-backup
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: distr-db-backup
                  key: S3_BUCKET
            - name: S3_PREFIX
              value: "distr-db-backup"
            - name: POSTGRES_HOST
              value: "distr-postgresql"
            - name: POSTGRES_DATABASE
              value: "distr"
            - name: POSTGRES_USER
              value: "distr"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: distr-db-secrets
                  key: password
            - name: BACKUP_KEEP_DAYS
              value: "60"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 65532
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            emptyDir: {}
          restartPolicy: OnFailure
