---
apiVersion: v1
kind: Secret
metadata:
  name: sso-secrets
  namespace: sso
type: Opaque
stringData:
  PG_HOST: postgresql-nuc-cluster.databases.svc.cluster.local
  PG_PASS: testpassword
  AUTHENTIK_SECRET_KEY: test-secret-key-123456789012345678901234567890
  PGUSERNAME: postgres
  PGPASSWORD: testpassword
