---
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-db-credentials
  namespace: sso
type: Opaque
stringData:
  ZITADEL_DATABASE_POSTGRES_HOST: postgresql-nuc-cluster.databases.svc.cluster.local
  ZITADEL_DATABASE_POSTGRES_PORT: "5432"
  ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
  ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
  ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: testpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-master-secrets
  namespace: sso
type: Opaque
stringData:
  masterkey: test-master-key-123456789012345678901234
