---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport-agent
  namespace: teleport-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: teleport-kube-agent
      version: 9.3.12
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    proxyAddr: teleport.fastnetserv.cloud:443
    kubeClusterName: "k8s-vms-daniele"
