---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-sc
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: ">=4.0.17"
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-chart
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nfs:
      server: 10.10.8.5
      path: /volume2/video
      volumeName: syno-nfs
    storageClass:
      name: synology
      reclaimPolicy: Retain
