# Auto-generated resources for gozzi-pve
# Generated by proxmox-generate-tf.py
# Review and adjust as needed before applying

#module "gozzi_pve_fw_bioadventures_eu_vm" {
#  source = "../../modules/proxmox-vm"
#  providers = {
#    proxmox = proxmox.gozzi_pve
#  }
#
#  name        = "fw.bioadventures.eu"
#  vmid        = 100
#  node_name   = "gozzi-pve"
#  description = "fw.bioadventures.eu"
#
#  cpu_cores = 4
#  cpu_type  = "host"
#  memory    = 6144
#
#  disks = [
#    {
#      datastore_id = "local-lvm"
#      size         = 32
#      interface    = "scsi0"
#    },
#    {
#      datastore_id = "local-lvm"
#      size         = 32
#      interface    = "ide2"
#    }
#  ]
#
#  network_devices = {
#    net0 = { bridge = "vmbr1", mac_address = "BC:24:11:03:14:A1" }
#  }
#
#  ip_config = {
#    ipv4_address = "dhcp"
#  }
#
#  ssh_keys = [
#    data.onepassword_item.ssh_public_key.public_key,
#    data.onepassword_item.ssh_public_key_new.public_key
#  ]
#
#  started       = true
#  start_on_boot = true
#
#  tags = ["firewall", "firewall.bioadventures.eu"]
#}

##module "gozzi_pve_web1_bioadventures_eu_vm" {
##  source = "../../modules/proxmox-vm"
##  providers = {
##    proxmox = proxmox.gozzi_pve
##  }
##
##  name        = "web1.bioadventures.eu"
##  vmid        = 201
##  node_name   = "gozzi-pve"
##  description = "web1.bioadventures.eu"
##
##  cpu_cores = 4
##  cpu_type  = "host"
##  memory    = 8192
##
##  disks = {
##    boot = {
##      datastore_id = "data-ssd"
##      interface    = "scsi0"
##      size         = 40
##      ssd          = false
##      discard      = "ignore"
##    }
##
##    data = {
##      datastore_id = "data-ssd"
##      interface    = "scsi1"
##      size         = 300
##      ssd          = false
##      discard      = "ignore"
##    }
##  }
##
##  boot_order = ["scsi0"]
##
##  network_devices = {
##    net0 = { bridge = "vmbr2", mac_address = "52:54:00:00:54:e9" }
##  }
##
##  ip_config = {
##    ipv4_address = "dhcp"
##  }
##
##  ssh_keys     = [
##    local.ssh_public_key,
##    local.ssh_public_key_new
##  ]
##
##  started       = true
##  start_on_boot = true
##
##  tags = ["debian", "webserver", "web1.bioadventures.eu"]
##}

module "gozzi_pve_okd_singlenode_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = "okd-singlenode"
  vmid        = 800
  node_name   = "gozzi-pve"
  description = "okd-singlenode"

  cpu_cores = 8
  cpu_type  = "host"
  memory    = 32768

  machine   = "q35"
  bios_type = "ovmf"

  efi_disk = {
    datastore_id      = "local-zfs"
    file_format       = "raw"
    pre_enrolled_keys = true
    type              = "4m"
  }

  disks = {
    boot = {
      backup       = false
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 150
      ssd          = false
      discard      = "ignore"
    }
  }

  boot_order = ["scsi0"]

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:89:55:B1" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm"]
}

##module "gozzi_pve_dckbio_1_bioadventures_eu_vm" {
##  source = "../../modules/proxmox-vm"
##  providers = {
##    proxmox = proxmox.gozzi_pve
##  }
##
##  name        = "dckbio-1.bioadventures.eu"
##  vmid        = 501
##  node_name   = "gozzi-pve"
##  description = "dckbio-1.bioadventures.eu"
##
##  cpu_cores = 8
##  cpu_type  = "host"
##  memory    = 8192
##
##  disks = {
##    boot = {
##      datastore_id = "data-ssd"
##      interface    = "virtio0"
##      size         = 20
##      ssd          = false
##      discard      = "ignore"
##    }
##
##    data = {
##      datastore_id = "data-ssd"
##      interface    = "virtio1"
##      size         = 100
##      ssd          = false
##      discard      = "ignore"
##    }
##
##    data = {
##      datastore_id = "data-ssd"
##      interface    = "virtio2"
##      size         = 2000
##      ssd          = false
##      discard      = "ignore"
##      type         = "qcow2"
##    }
##  }
##
##  network_devices = {
##    net0 = { bridge = "vmbr1", mac_address = "BC:24:11:AF:DE:D1" }
##  }
##
##  ip_config = {
##    ipv4_address = "dhcp"
##  }
##
##  ssh_keys     = [
##    local.ssh_public_key,
##    local.ssh_public_key_new
##  ]
##
##  started       = true
##  start_on_boot = true
##
##  tags = ["automation", "bckbio-1", "debian"]
##}
##
##module "gozzi_pve_dolibarr_bioadventures_eu_vm" {
##  source = "../../modules/proxmox-vm"
##  providers = {
##    proxmox = proxmox.gozzi_pve
##  }
##
##  name        = "dolibarr.bioadventures.eu"
##  vmid        = 203
##  node_name   = "gozzi-pve"
##  description = "dolibarr.bioadventures.eu"
##
##  cpu_cores = 2
##  cpu_type  = "host"
##  memory    = 2048
##
##  disks = {
##    boot = {
##      datastore_id = "data-ssd"
##      interface    = "scsi0"
##      size         = 32
##      ssd          = false
##      discard      = "ignore"
##    }
##  }
##
##  network_devices = {
##    net0 = { bridge = "vmbr1", mac_address = "52:54:00:32:1e:f9" }
##  }
##
##  ip_config = {
##    ipv4_address = "dhcp"
##  }
##
##  ssh_keys     = [
##    local.ssh_public_key,
##    local.ssh_public_key_new
##  ]
##
##  started       = true
##  start_on_boot = true
##
##  tags = ["dolibarr", "ubuntu"]
##}

module "gozzi_pve_r_3cx_bioadventures_eu_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = "3cx.bioadventures.eu"
  vmid        = 204
  node_name   = "gozzi-pve"
  description = "3cx.bioadventures.eu"

  protection = true

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 2048

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 20
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr1", mac_address = "52:54:00:7d:02:28" }
    net1 = { bridge = "vmbr0", mac_address = "52:54:00:6a:db:10" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["debian", "3cx", "voip"]
}

module "gozzi_pve_kubenuc_m2_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = "kubenuc-m2"
  vmid        = 102
  node_name   = "gozzi-pve"
  description = "kubenuc-m2"

  cpu_cores = 1
  cpu_sockets = 2
  cpu_type  = "host"
  memory    = 6144

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 20
      ssd          = true
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:63:66:14" }
  }

  ip_config = {
    ipv4_address = "10.20.0.10/24"
    ipv4_gateway = "10.20.0.254"
  }

  cloud_init_datastore_id = "data-ssd"

  ssh_keys     = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true
  protection    = true

  tags = ["automation", "vm", "kubernetes"]
}

module "gozzi_pve_pve_backup_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = "pve-backup"
  vmid        = 1000
  node_name   = "gozzi-pve"
  description = "pve-backup"

  cpu_cores   = 2
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 4096

  disks = {
    boot = {
      datastore_id = "local-zfs"
      interface    = "scsi0"
      size         = 32
      ssd          = false
      discard      = "ignore"
    }

    data = {
      datastore_id = "vm-backups"
      interface    = "scsi1"
      size         = 1000
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr1", mac_address = "BC:24:11:E5:E0:94" }
    net1 = { bridge = "vmbr3", mac_address = "BC:24:11:F8:F5:CF" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm", "backup"]
}

##module "gozzi_pve_mail1_bioadventures_eu_vm" {
##  source = "../../modules/proxmox-vm"
##  providers = {
##    proxmox = proxmox.gozzi_pve
##  }
##
##  name        = "mail1.bioadventures.eu"
##  vmid        = 202
##  node_name   = "gozzi-pve"
##  description = "mail1.bioadventures.eu"
##
##  cpu_cores = 2
##  cpu_type  = "host"
##  memory    = 8192
##
##  disks = {
##    boot = {
##      datastore_id = "data-ssd"
##      interface    = "scsi0"
##      size         = 20
##      ssd          = false
##      discard      = "ignore"
##    }
##
##    data = {
##      datastore_id = "data-ssd"
##      interface    = "scsi1"
##      size         = 70
##      ssd          = false
##      discard      = "ignore"
##    }
##  }
##
##  network_devices = {
##    net0 = { bridge = "vmbr2", mac_address = "52:54:00:61:90:56" }
##  }
##
##  ip_config = {
##    ipv4_address = "dhcp"
##  }
##
##  ssh_keys     = [
##    local.ssh_public_key,
##    local.ssh_public_key_new
##  ]
##
##  started       = true
##  start_on_boot = true
##
##  tags = ["debian", "mail1.bioadventures.eu", "mailserver"]
##}
##
##module "gozzi_pve_kubenuc_w2_vm" {
##  source = "../../modules/proxmox-vm"
##  providers = {
##    proxmox = proxmox.gozzi_pve
##  }
##
##  name        = "kubenuc-w2"
##  vmid        = 103
##  node_name   = "gozzi-pve"
##  description = "kubenuc-w2"
##
##  cpu_cores = 8
##  cpu_type  = "x86-64-v2-AES"
##  memory    = 16384
##
##  disks = {
##    boot = {
##      datastore_id = "data-ssd"
##      interface    = "scsi0"
##      size         = 30
##      ssd          = false
##      discard      = "ignore"
##    }
##
##    data = {
##      datastore_id = "data-ssd"
##      interface    = "scsi1"
##      size         = 550
##      ssd          = false
##      discard      = "ignore"
##    }
##  }
##
##  network_devices = {
##    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:F9:FF:F6" }
##  }
##
##  ip_config = {
##    ipv4_address = "dhcp"
##  }
##
##  ssh_keys     = [
##    local.ssh_public_key,
##    local.ssh_public_key_new
##  ]
##
##  started       = true
##  start_on_boot = true
##
##  tags = ["automation", "vm"]
##}
