# Auto-generated resources for gozzi-pve
# Generated by proxmox-generate-tf.py
# Review and adjust as needed before applying

module "gozzi_pve_fw_bioadventures_eu_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.fw
  vmid        = 100
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.fw

  protection = true

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 6144

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 45
      ssd          = false
      discard      = "ignore"
    }
  }

  # net0=vmbr1(LAN), net1=vmbr2(DMZ), net2=vmbr0(WAN), net3=vmbr4(LAN
  # Testing), net4=vmbr5(DMZ Testing) - bridge->segment mapping confirmed
  # against the live host's own bridge comments (get_node_network), not
  # guessed; user-confirmed before drafting this block. This firewall VM
  # is the same physical device already registered in NetBox as the
  # sophos-xg-lug dcim.device (its 5 ports already carry these live IPs)
  # - deliberately NOT also registered as a netbox_virtual_machine here,
  # to avoid duplicate-registering the same real-world device.
  network_devices = {
    net0 = { bridge = "vmbr1", mac_address = "52:54:00:14:24:1a" }
    net1 = { bridge = "vmbr2", mac_address = "52:54:00:2b:36:f3" }
    net2 = { bridge = "vmbr0", mac_address = "52:54:00:66:b7:79" }
    net3 = { bridge = "vmbr4", mac_address = "52:54:00:2e:a7:22" }
    net4 = { bridge = "vmbr5", mac_address = "52:54:00:db:c1:8f" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["firewall", "firewall.bioadventures.eu"]
}

module "gozzi_pve_web1_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.web1
  vmid        = 201
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.web1

  protection = true

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 8192

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 40
      ssd          = false
      discard      = "ignore"
    }

    data = {
      datastore_id = "data-ssd"
      interface    = "scsi1"
      size         = 300
      ssd          = false
      discard      = "ignore"
    }
  }

  boot_order = ["scsi0"]

  network_devices = {
    net0 = { bridge = "vmbr2", mac_address = "52:54:00:00:54:e9" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["debian", "webserver", local.gozzi_hpelvisor_secrets.gozzi_pve.vm.web1]
}

module "gozzi_pve_okd_singlenode_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.okd_singlenode
  vmid        = 800
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.okd_singlenode

  cpu_cores = 8
  cpu_type  = "host"
  memory    = 32768

  machine   = "q35"
  bios_type = "ovmf"

  efi_disk = {
    datastore_id      = "local-zfs"
    file_format       = "raw"
    pre_enrolled_keys = true
    type              = "4m"
  }

  disks = {
    boot = {
      backup       = false
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 150
      ssd          = false
      discard      = "ignore"
    }
  }

  boot_order = ["scsi0"]

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:89:55:B1" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm"]
}

module "gozzi_pve_dckbio_1_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.dckbio_1
  vmid        = 501
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.dckbio_1

  protection = true

  cpu_cores = 8
  cpu_type  = "host"
  memory    = 8192

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "virtio0"
      size         = 20
      ssd          = false
      discard      = "ignore"
    }

    data = {
      datastore_id = "data-ssd"
      interface    = "virtio1"
      size         = 100
      ssd          = false
      discard      = "ignore"
    }

    vmbackup = {
      datastore_id = "vm-backups"
      interface    = "virtio2"
      size         = 2000
      ssd          = false
      discard      = "ignore"
      file_format  = "qcow2"
      backup       = false
      iothread     = false
    }
  }

  boot_order = ["virtio0", "net0"]

  network_devices = {
    net0 = { bridge = "vmbr1", mac_address = "BC:24:11:AF:DE:D1" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  cloud_init_datastore_id = "data-ssd"
  cloud_init_user         = "daniele"

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "bckbio-1", "debian"]
}

module "gozzi_pve_dolibarr_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.dolibarr
  vmid        = 203
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.dolibarr

  protection = true

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 2048

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 32
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr1", mac_address = "52:54:00:32:1e:f9" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["dolibarr", "ubuntu"]
}

module "gozzi_pve_r_3cx_bioadventures_eu_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm["3cx_bioadventures"]
  vmid        = 204
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm["3cx_bioadventures"]

  protection = true

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 2048

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 20
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr1", mac_address = "52:54:00:7d:02:28" }
    net1 = { bridge = "vmbr0", mac_address = "52:54:00:6a:db:10" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["debian", "3cx", "voip"]
}

module "gozzi_pve_kubenuc_m2_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.kubenuc_m2
  vmid        = 102
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.kubenuc_m2

  cpu_cores   = 1
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 6144

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 20
      ssd          = true
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:63:66:14" }
  }

  ip_config = {
    ipv4_address = "10.20.0.10/24"
    ipv4_gateway = "10.20.0.254"
  }

  cloud_init_datastore_id = "data-ssd"

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true
  protection    = true

  tags = ["automation", "vm", "kubernetes"]
}

module "gozzi_pve_pve_backup_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.pve_backup
  vmid        = 1000
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.pve_backup

  cpu_cores   = 2
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 4096

  disks = {
    boot = {
      datastore_id = "local-zfs"
      interface    = "scsi0"
      size         = 32
      ssd          = false
      discard      = "ignore"
    }

    data = {
      datastore_id = "vm-backups"
      interface    = "scsi1"
      size         = 1000
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr1", mac_address = "BC:24:11:E5:E0:94" }
    net1 = { bridge = "vmbr3", mac_address = "BC:24:11:F8:F5:CF" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["automation", "vm", "backup"]
}

module "gozzi_pve_mail1_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.mail1
  vmid        = 202
  node_name   = "gozzi-pve"
  description = local.gozzi_hpelvisor_secrets.gozzi_pve.vm.mail1

  protection = true

  cpu_cores = 2
  cpu_type  = "host"
  memory    = 8192

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi0"
      size         = 20
      ssd          = false
      discard      = "ignore"
    }

    data = {
      datastore_id = "data-ssd"
      interface    = "scsi1"
      size         = 70
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr2", mac_address = "52:54:00:61:90:56" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["debian", local.gozzi_hpelvisor_secrets.gozzi_pve.vm.mail1, "mailserver"]
}

module "gozzi_pve_kubenuc_w2_vm" {
  source = "github.com/dark-vex/terraform-proxmox-vm?ref=1302f332cf44d3ec261c50663ba64c74ae7513b5" # v1.0.0
  providers = {
    proxmox = proxmox.gozzi_pve
  }

  name        = "kubenuc-w2"
  vmid        = 103
  node_name   = "gozzi-pve"
  description = "kubenuc-w2"

  cpu_cores   = 4
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 16384

  disks = {
    boot = {
      datastore_id = "data-ssd"
      interface    = "scsi1"
      size         = 30
      ssd          = true
      discard      = "ignore"
    }

    data = {
      datastore_id = "data-ssd"
      interface    = "scsi3"
      size         = 550
      ssd          = true
      discard      = "ignore"
    }
  }

  boot_order = ["scsi1"]

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:F9:FF:F6" }
  }

  ip_config = {
    ipv4_address = "10.20.0.11/24"
    ipv4_gateway = "10.20.0.254"
  }

  cloud_init_datastore_id = "local-zfs"
  cloud_init_user         = "daniele"
  cloud_init_dns = {
    servers = ["10.20.0.254"]
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true
  protection    = true

  tags = ["automation", "kubernetes", "vm"]
}
