# Auto-generated imports for gozzi-pve
# Generated by proxmox-generate-tf.py

#import {
#  to = module.gozzi_pve_fw_bioadventures_eu_vm.proxmox_virtual_environment_vm.this
#  id = "gozzi-pve/100"
#}

##import {
##  to = module.gozzi_pve_web1_bioadventures_eu_vm.proxmox_virtual_environment_vm.this
##  id = "gozzi-pve/201"
##}

import {
  to = module.gozzi_pve_okd_singlenode_vm.proxmox_virtual_environment_vm.this
  id = "gozzi-pve/800"
}

##import {
##  to = module.gozzi_pve_dckbio_1_bioadventures_eu_vm.proxmox_virtual_environment_vm.this
##  id = "gozzi-pve/501"
##}
##
##import {
##  to = module.gozzi_pve_dolibarr_bioadventures_eu_vm.proxmox_virtual_environment_vm.this
##  id = "gozzi-pve/203"
##}
##
##import {
##  to = module.gozzi_pve_r_3cx_bioadventures_eu_vm.proxmox_virtual_environment_vm.this
##  id = "gozzi-pve/204"
##}

import {
  to = module.gozzi_pve_kubenuc_m2_vm.proxmox_virtual_environment_vm.this
  id = "gozzi-pve/102"
}

import {
  to = module.gozzi_pve_pve_backup_vm.proxmox_virtual_environment_vm.this
  id = "gozzi-pve/1000"
}

##import {
##  to = module.gozzi_pve_mail1_bioadventures_eu_vm.proxmox_virtual_environment_vm.this
##  id = "gozzi-pve/202"
##}
##
##import {
##  to = module.gozzi_pve_kubenuc_w2_vm.proxmox_virtual_environment_vm.this
##  id = "gozzi-pve/103"
##}
