# Auto-generated resources for hpelvisor
# Generated by proxmox-generate-tf.py
# Review and adjust as needed before applying

module "hpelvisor_gitlab_ddlns_net_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  hostname    = "gitlab.ddlns.net"
  vmid        = 700
  node_name   = "hpelvisor"
  description = "gitlab.ddlns.net"

  cpu_cores      = 8
  memory         = 12288
  swap           = 4096
  disk_size      = 50
  disk_datastore = "data-hdd"

  template_file_id = proxmox_virtual_environment_download_file.hpelvisor_ubuntu_24_04_lxc.id
  os_type          = "debian"

  network_bridge         = "vmbr5"
  network_mac_address    = "BC:24:11:CB:4F:4F"
  network_interface_name = "eth0"

  ip_config = {
    ipv4_address = "10.20.0.47/24"
    ipv4_gateway = "10.20.0.254"
    ipv6_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  password     = data.onepassword_item.lxc_access.password
  unprivileged = true

  console = {
    enabled = true
  }

  started       = true
  start_on_boot = true

  tags = ["automation", "lxc"]
}

module "hpelvisor_dolibarr_test_bioadventures_eu_lxc" {
  source = "../../modules/proxmox-lxc"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  hostname    = "dolibarr.test.bioadventures.eu"
  vmid        = 701
  node_name   = "hpelvisor"
  description = "dolibarr.test.bioadventures.eu"

  cpu_cores      = 2
  memory         = 2048
  swap           = 2048
  disk_size      = 50
  disk_datastore = "data-hdd"

  template_file_id = proxmox_virtual_environment_download_file.hpelvisor_ubuntu_24_04_lxc.id
  os_type          = "debian"

  network_bridge         = "vmbr5"
  network_mac_address    = "BC:24:11:BE:28:FA"
  network_interface_name = "eth0"

  ip_config = {
    ipv4_address = "dhcp"
    ipv6_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  password     = data.onepassword_item.lxc_access.password
  unprivileged = false

  console = {
    enabled = true
  }

  started       = true
  start_on_boot = false

  tags = ["automation", "lxc"]
}

module "hpelvisor_gen8_runner_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "gen8-runner"
  vmid        = 3000
  node_name   = "hpelvisor"
  description = "gen8-runner"

  cpu_cores   = 8
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 16400

  disks = {
    boot = {
      datastore_id = "data-hdd"
      interface    = "scsi0"
      size         = 138
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:D7:3C:0E" }
  }

  cloud_init_datastore_id = "data-hdd"

  ip_config = {
    ipv4_address = "dhcp"
    ipv6_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  tags = ["runner"]
}

module "hpelvisor_sensor_debian12_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "sensor-debian12"
  vmid        = 703
  node_name   = "hpelvisor"
  description = "sensor-debian12"

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 4096

  disks = {
    boot = {
      datastore_id = "data-hdd"
      interface    = "scsi0"
      size         = 50
      ssd          = false
      discard      = "ignore"
    }
  }

  cloud_init_datastore_id = "data-hdd"

  agent_enabled = false

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:9F:83:9D" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = false

  tags = ["automation", "vm"]
}

module "hpelvisor_pelican_game_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "pelican-game"
  vmid        = 7003
  node_name   = "hpelvisor"
  description = "pelican-game"

  cpu_cores   = 4
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 8192

  disks = {
    boot = {
      datastore_id = "data-hdd"
      backup       = false
      interface    = "scsi0"
      size         = 50
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:C2:B8:49" }
  }

  ip_config = {
    ipv4_address = "dhcp"
    ipv6_address = "dhcp"
  }

  cloud_init_datastore_id = "data-hdd"

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = false

  tags = ["automation", "vm"]
}

module "hpelvisor_prod_k3s_worker1_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "prod-k3s-worker1"
  vmid        = 601
  node_name   = "hpelvisor"
  description = "prod-k3s-worker1"

  cpu_cores   = 4
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 12288

  disks = {
    boot = {
      datastore_id = "data-hdd"
      interface    = "scsi0"
      size         = 50
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "52:54:00:5b:bf:e3" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  protection = true

  tags = ["automation", "vm", "kubernetes"]
}

module "hpelvisor_openstack_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "openstack"
  vmid        = 900
  node_name   = "hpelvisor"
  description = "openstack"

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 16454

  disks = {
    boot = {
      datastore_id = "data-hdd"
      interface    = "scsi0"
      size         = 153
      ssd          = false
      discard      = "ignore"
    }

    data = {
      datastore_id = "data-hdd"
      interface    = "scsi1"
      size         = 158
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:00:09:6D" }
  }

  ip_config = {
    ipv4_address = "dhcp"
    ipv6_address = "dhcp"
  }

  cloud_init_datastore_id = "data-hdd"
  cloud_init_dns = {
    servers = ["10.20.0.254"]
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = false
  start_on_boot = false

  tags = ["automation", "vm"]
}

module "hpelvisor_openstack_snap_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "openstack-snap"
  vmid        = 2000
  node_name   = "hpelvisor"
  description = "openstack-snap"

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 16454

  disks = {
    boot = {
      datastore_id = "data-hdd"
      interface    = "scsi0"
      size         = 3
      ssd          = false
      discard      = "ignore"
    }

    data = {
      datastore_id = "data-hdd"
      interface    = "scsi1"
      size         = 8
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:3F:AC:17" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = false
  start_on_boot = false

  tags = ["automation", "vm"]
}

module "hpelvisor_sensor_ubuntu24_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "sensor-ubuntu24"
  vmid        = 702
  node_name   = "hpelvisor"
  description = "sensor-ubuntu24"

  cpu_cores = 4
  cpu_type  = "host"
  memory    = 8192

  disks = {
    boot = {
      datastore_id = "data-hdd"
      interface    = "scsi0"
      size         = 43
      ssd          = false
      discard      = "ignore"
    }
  }

  cloud_init_datastore_id = "data-hdd"
  #cloud_init_file_id      = "local:snippets/ubuntu.cloud-config.yaml"

  agent_enabled = false

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:6A:1D:97" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = false

  tags = ["automation", "vm"]
}

module "hpelvisor_prod_k3s_master_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "prod-k3s-master"
  vmid        = 600
  node_name   = "hpelvisor"
  description = "prod-k3s-master"

  cpu_cores   = 2
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 6144

  disks = {
    boot = {
      datastore_id = "data-hdd"
      interface    = "scsi0"
      size         = 50
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "52:54:00:50:9e:8b" }
  }

  ip_config = {
    ipv4_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = true

  protection = true

  tags = ["automation", "vm", "kubernetes"]
}

module "hpelvisor_amp_game_vm" {
  source = "../../modules/proxmox-vm"
  providers = {
    proxmox = proxmox.hpelvisor
  }

  name        = "amp-game"
  vmid        = 7000
  node_name   = "hpelvisor"
  description = "amp-game"

  cpu_cores   = 4
  cpu_sockets = 2
  cpu_type    = "host"
  memory      = 8192

  disks = {
    boot = {
      datastore_id = "data-hdd"
      backup       = false
      interface    = "scsi0"
      size         = 50
      ssd          = false
      discard      = "ignore"
    }
  }

  network_devices = {
    net0 = { bridge = "vmbr5", mac_address = "BC:24:11:03:14:A1" }
  }

  cloud_init_datastore_id = "data-hdd"

  ip_config = {
    ipv4_address = "dhcp"
    ipv6_address = "dhcp"
  }

  ssh_keys = [
    local.ssh_public_key,
    local.ssh_public_key_new
  ]

  started       = true
  start_on_boot = false

  tags = ["automation", "vm"]
}
