---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: harbor
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: redis
      version: ">=19.5.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami-chart
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    auth:
      enabled: false
    master:
      persistence:
        storageClass: longhorn
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: redis
              app.kubernetes.io/component: replica
    replica:
      persistence:
        storageClass: longhorn
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: redis
              app.kubernetes.io/component: replica
