---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-update-strategy
  namespace: flux-system
spec:
  dependsOn:
    - name: harbor
  patches:
    - patch: |
        - op: replace
          path: /spec/strategy/rollingUpdate/maxSurge
          value: 1
      target:
        kind: Deployment
        name: harbor-core
    - patch: |
        - op: replace
          path: /spec/strategy/rollingUpdate/maxUnavailable
          value: 1
      target:
        kind: Deployment
        name: harbor-core
    - patch: |
        - op: replace
          path: /spec/strategy/rollingUpdate/maxSurge
          value: 1
      target:
        kind: Deployment
        name: harbor-portal
    - patch: |
        - op: replace
          path: /spec/strategy/rollingUpdate/maxUnavailable
          value: 1
      target:
        kind: Deployment
        name: harbor-portal
