---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: distr-chart
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/distr-sh/charts
  timeout: 3m
  type: "oci"
