---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-operator-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  timeout: 3m
