{
 "title": "Harbor — kubenuc",
 "tags": [
  "kubenuc",
  "harbor",
  "registry",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "component up status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "harbor_up{cluster=\"kubenuc\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Quota Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte{cluster=\"kubenuc\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "project members",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_project_member_total{cluster=\"kubenuc\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Project repo total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_project_repo_total{cluster=\"kubenuc\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "artifacts pulled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_artifact_pulled{cluster=\"kubenuc\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  { "title": "JobService Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "task latency",
   "type": "timeseries",
   "description": "time period from last process of task queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "harbor_task_queue_latency{cluster=\"kubenuc\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "task concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_task_concurrency{cluster=\"kubenuc\"}",
     "legendFormat": "{{type}} pool={{pool}}"
    }
   ]
  },
  {
   "title": "task queue pending size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_task_queue_size{cluster=\"kubenuc\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "tasks per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(harbor_task_scheduled_total{cluster=\"kubenuc\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "number of running scheduled jobs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_task_scheduled_total{cluster=\"kubenuc\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Registry Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Registry request inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{cluster=\"kubenuc\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Registry request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(registry_http_requests_total{cluster=\"kubenuc\"}[5m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "registry request time 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_request_duration_seconds_bucket{cluster=\"kubenuc\"}[10m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "registry request size 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_request_size_bytes_bucket{cluster=\"kubenuc\"}[10m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "registry response size 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_response_size_bytes_bucket{cluster=\"kubenuc\"}[10m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}