---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bareos-dir-config-vol
  namespace: bareos
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-hostpath
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bareos-dir-catalog-vol
  namespace: bareos
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-hostpath
  volumeMode: Filesystem