---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s3
  namespace: nextcloud-fastnetserv
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: seaweedfs
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    master:
      replicaCount: 1
      persistence:
        storageClass: "openebs-hostpath"
        size: 100Mi

    volume:
      replicaCount: 3
      persistence:
        storageClass: "openebs-hostpath"
        size: 10Gi

    filer:
      replicaCount: 1
      persistence:
        storageClass: "openebs-hostpath"
        size: 100Mi

    s3:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "haproxy"
        hostname: ${S3_API_HOST}
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          haproxy.org/request-body-size: "500m"
        tls: true
