# This manifest was generated for kind CI testing
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: claude/issue-465-20251121-2300
  url: https://github.com/dark-vex/infra-cd.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/kubenuc-kind
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
