---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 5m
  chart:
    spec:
      chart: crowdsec
      version: ">=0.5.0 <0.9.0"
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    agent:
      acquisition:
        # -- Specify each pod you want to process it logs (namespace, podName and program)
        - namespace: "ingress-nginx"
          # -- to select pod logs to process
          podName: "ingress-nginx-controller-*"
          # -- program name related to specific parser you will use (see https://hub.crowdsec.net/author/crowdsecurity/configurations/docker-logs)
          program: "nginx"
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/nginx"
      # -- Enable persistent volumes
      persistentVolume:
        # -- Persistent volume for config folder. Stores local config (parsers, scenarios etc.)
        config:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: "local-hostpath"
          size: 100Mi
    lapi:
      dashboard:
        enabled: true
      persistentVolume:
        # -- Persistent volume for data folder. Stores e.g. registered bouncer api keys
        data:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: "local-hostpath"
          size: 1Gi
        # -- Persistent volume for config folder. Stores e.g. online api credentials
        config:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: "local-hostpath"
          size: 100Mi
