---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teleport-kube-agent-join-token
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/k3s-rabbit/apps/teleport-agent/secrets
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teleport-kube-agent
  namespace: flux-system
spec:
  dependsOn:
    - name: teleport-kube-agent-join-token
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/k3s-rabbit/apps/teleport-agent/manifests
  prune: true
