---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: falco-test
    image: debian:12
    pre_build_image: true
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      falco-test:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
