---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/jellyfin/manifests
  prune: true
  dependsOn:
    - name: openebs
  patches:
    - target:
        kind: HelmRelease
        name: jellyfin
      patch: |
        - op: replace
          path: /spec/values/ingress/main/hosts/0/host
          value: tv.tst.ddlns.net
        - op: replace
          path: /spec/values/ingress/main/tls/0/hosts/0
          value: tv.tst.ddlns.net
        - op: replace
          path: /spec/values/ingress/main/tls/0/secretName
          value: jellyfin-tst-tls
