---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud-fastnetserv
type: Opaque
stringData:
  server: postgresql-nuc-cluster.databases.svc.cluster.local
  database: nextcloud
  pgdb-username: nextcloud
  pgdb-password: testpassword
