---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: intel-gpu-plugin
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.29.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 6
      strategy: rollback
  values:
    env:
      TZ: "Europe/Rome"
    common:
      nodeSelector:
        gputype: "intel"
