---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-deploy
  namespace: sysdig-agent
spec:
  maxHistory: 20
  interval: 15m
  chart:
    spec:
      chart: shield
      version: "1.3.0"
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
    timeout: 30m
  upgrade:
    remediation:
      retries: 50
    timeout: 30m
  values:
    cluster_config:
      name: ranchernuc
    sysdig_endpoint:
      region: eu1
      access_key_existing_secret: "sysdig-agent"
      secure_api_token_existing_secret: "sysdig-agent-api"
    host:
      driver: universal_ebpf
      resources:
        shield:
          limits:
            memory: 4Gi
      additional_settings:
        feature:
          mode: troubleshooting
        cri:
          socket_path: /run/k3s/containerd/containerd.sock
        log:
          #file_priority: info
          #console_priority: info
          #event_priority: info
          file_priority: warning
          console_priority: warning
          event_priority: warning
          #file_priority_by_component:
          #  - "cm_socket_endpoint: debug"
          #  - "endpoint: debug: debug"
          #  - "conn_mgr: debug: debug"
          #  - "connection_manager: debug"
          #  - "cm_collector_endpoint: debug"
    features:
      monitoring:
        prometheus:
          enabled: true
          prometheus_yaml:
            global:
              scrape_interval: 10s
            scrape_configs:
            - job_name: 'nut'
              static_configs:
              # Insert NUT server address here
              - targets: ['10.10.8.5:3493']
              metrics_path: /metrics
              relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                # Insert NUT exporter address here
                replacement: 10.10.8.20:9995
      posture:
        cluster_posture:
          enabled: true
        host_posture:
          enabled: true
      responding:
        rapid_response:
          # Disable on 0.3.1 it's not supported the password in an external secret
          enabled: false
      vulnerability_management:
        container_vulnerability_management:
          enabled: true
        host_vulnerability_management:
          enabled: true
        in_use:
          enabled: true
      detections:
        drift_control:
          enabled: true
        malware_control:
          enabled: true
        ml_policies:
          enabled: true
        kubernetes_audit:
          enabled: true
      admission_control:
        enabled: false
      investigations:
        activity_audit:
          enabled: true
        live_logs:
          enabled: true
        captures:
          enabled: true
