---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-admission-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: admission-controller
      version: 0.6.2
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    sysdig:
      existingSecureAPITokenSecret: "sysdig-admission-controller-webhook"
      url: https://eu1.app.sysdig.com
    clusterName: ranchernuc
    features:
      k8sAuditDetections: true
    scanner:
      enabled: false
