---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-deploy
  namespace: sysdig-agent
spec:
  chart:
    spec:
      chart: sysdig-deploy
      version: ">=1.3.29"
  values:
    global:
      clusterConfig:
        name: "ranchernuc"
      sysdig:
        region: "eu1"
      kspm:
        deploy: true

    agent:
      sysdig:
        settings:
          app_checks:
            - name: nginx
              enabled: false
            - name: apache
              enabled: false
            - name: redis
              enabled: false
          cri:
            socket_path: /run/k3s/containerd/containerd.sock
            delay_ms: 500
          #enforce container engine
          #container_engines:
          #  mesos: false
          #  bpm: false
          #  libvirt_lxc: false
          #  lxc: false
          #  rkt: false
          #  docker: false
          #  podman: false
          #  cri: true
          log:
            file_priority: warning
            console_priority: info
            event_priority: warning
          prometheus:
            enabled: true
            prom_service_discovery: true
          jmx:
            enabled: false

    nodeAnalyzer:
      nodeAnalyzer:
        imageAnalyzer:
          containerdSocketPath: unix:///run/k3s/containerd/containerd.sock
          extraVolumes:
            volumes:
              - name: socketpath
                hostPath:
                  path: /run/k3s/containerd/containerd.sock
                  type: ""
        benchmarkRunner:
          resources:
            limits:
              cpu: 250m
        runtimeScanner:
          deploy: true
          resources:
            limits:
              cpu: 300m
          settings:
            eveEnabled: true
          extraMounts:
            - name: socketpath
              mountPath: /var/run/containerd/containerd.sock
