---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-admission-controller
spec:
  chart:
    spec:
      chart: admission-controller
      version: ">=0.6.24"
  values:
    sysdig:
      existingSecureAPITokenSecret: "sysdig-admission-controller-webhook"
      url: https://secure.sysdig.com
    clusterName: k8s-daniele-vms 
    features:
      k8sAuditDetections: true
    scanner:
      enabled: false
