---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: webhook
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-webhook-config
  namespace: webhook
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        # Enable JSON log format
        log_format json_log escape=json '{"source": "nginx", "time": $msec, "resp_body_size": $body_bytes_sent, "host": "$http_host", "address": "$remote_addr", "request_length": $request_length, "method": "$request_method", "uri": "$request_uri", "status": $status,  "user_agent": "$http_user_agent", "resp_time": $request_time, "upstream_addr": "$upstream_addr"}';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
  webhook.conf: |
    server {
        listen       80;
        server_name  webhook.ddlns.net;
        access_log   /var/log/nginx/main-access.log;
        error_log    /var/log/nginx/main-error.log;

        location /webhook-test {
            client_body_buffer_size 1024k;
            access_log   /var/log/nginx/webhook-access.log json_log;
            default_type application/json;
            proxy_pass http://127.0.0.1:12001;
        }
    }

    # echo server.
    server {
        listen 12001;
        server_name 127.0.0.1;
        location / {
            default_type application/json;
            return 200 '{"code": 200}';
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-webhook
  name: nginx-webhook
  namespace: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webhook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-webhook
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: webhook-config
          mountPath: /etc/nginx/conf.d/webhook.conf
          subPath: webhook.conf
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: webhook-config
        configMap:
          name: nginx-webhook-config
          items:
          - key: webhook.conf
            path: webhook.conf
      - name: nginx-config
        configMap:
          na
            me: nginx-webhook-config
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-webhook
  name: nginx-webhook-service
  namespace: webhook
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-webhook
  sessionAffinity: None
  type: NodePort
