---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 15m
  chart:
    spec:
      chart: portainer
      version: ">=1.0.35"
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    enterpriseEdition:
      enabled: true

    service:
      type: ClusterIP

    tls:
      force: true

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: portainer.ddlns.net
          paths:
            - path: /

    persistence:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteOnce

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
