---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-community-charts
      version: ">=7.1.0 <7.2.0"
  values:
    podAnnotations: {}
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
