#ENC[AES256_GCM,data:M01Nv+uMh/akfP+OJytu4iUUv30MAo4Jq/tE2yojBaHsbS09UBj9jCLTTWTHIgug+zPvl4Ym0/9N,iv:WtMi7OZhCBERiIVh88WTUoSOpdzzKU/hEuP+6OuGy20=,tag:49E55p3GVI5QV7SH2PiOGw==,type:comment]
#ENC[AES256_GCM,data:47pyQzb0S3oOwv9ELQwkV7j/KjPHfcULLOHlf3g4gYbM8Fbi49nh8EPMJzgrnfDhOtzTsM/u59msJws9Bc1DMIW0NUroRR+0Fa8jQlDPm2o+,iv:/YY4kI2C4tNZvESarL4DhfVerrOTwb1a8ODOiNS1pb0=,tag:Xl6dGYs/YKTA5cDUxH6zxw==,type:comment]
#
#ENC[AES256_GCM,data:En8u41HJFCwwqZnbez3d4h6f5baUf0DH0bWDbz14cw8X/8qdwkBUvw==,iv:8fDl4jb/dgTTPoCLQwYPtW8/gi/+Tx2lHlbIN7TXmic=,tag:WOUqJz82Mph7rhIQtCDRPA==,type:comment]
#ENC[AES256_GCM,data:FNt688CEAhbB0y8HaJ2pFOwFYyBuqAiZCjdG1jfOYLuhimYMyAzs,iv:7ut3R0mALAq678F2goXPMLG1QeJHaD9upO35ni2J290=,tag:rwyAkBPW1rmvtgMcQwHF2A==,type:comment]
#ENC[AES256_GCM,data:ombcv8Gxwj/v9gm+XmSWDYElWpw0O1HnO7WFMIgHGCK+w7j8igZjdRa3Eg==,iv:curVMyFdRHddizruLTNSzPADp+Yd047SmJYeYYvwBuc=,tag:5LtPutICHg//RowmKn1iyQ==,type:comment]
#ENC[AES256_GCM,data:uTGqz+apPL8pWC9i399J8VrcmDaOEc9acSpmSlzt,iv:nOUbgUSbzn+Tf7/ubI0tpOrh1+PVdy2AQlPLWpsfBdg=,tag:CfO3YivZ9IuFRg8XauGsrQ==,type:comment]
#ENC[AES256_GCM,data:N+Qh6QD7fQLclmQ0qptcBG/q83uRN7xv8MnjUOYlCgSbwc8Wh+Yl1gkYP5HiD6nLQouiug==,iv:zQCluKZSm0HYtufhGl5i7oiNY8XFa0prHkPpRbcB4Z8=,tag:BJEq9+iyzxr/NvebuCfIdQ==,type:comment]
#ENC[AES256_GCM,data:Z797wGVb6KVGS36CHUYkV5cxVY7Y9CaCbAqZCCFKW2dzTmqNYQ==,iv:5U3Z7sNhT7kLfbQT6cEsQccFdk3h5EHeezaTO+xpJDo=,tag:NFY3jLe9r1dz95SrUwqTIg==,type:comment]
#ENC[AES256_GCM,data:4iJ7lf+zI4WeykQ0m2iGYwKhmpNPi5L4tOelRyF8eVLTwFGgRJOCcvKfA8UxYrUjVI/eXpc4YVZM5kkjVSCrQ8rsZg==,iv:9R1/Mg5keKUWdoYrlQIepSA0YxJ8Q6Purah0XfRaIs0=,tag:iTjSabmxA7ZZ8/3tgV7U5A==,type:comment]
#ENC[AES256_GCM,data:7J886WVQTslsrc+CxWTYjzo3R+MPh3feLchb7MSaS5Y6w90rn485ivmnxc7tEP70m5DbFbJ0FL2+hw==,iv:xEe0ev3hWfgN8j0aodcR1HlLBMFhg+vklhANjroqyzw=,tag:sHRkI7FMLeQSIqsxpNGZpw==,type:comment]
apiVersion: ENC[AES256_GCM,data:oXU=,iv:JBekRZcNTlCFp+2Zjv+wPLTlKXmzf10UMcnLDK2PHx0=,tag:gN0Gn+RNTT8gC2ppWkqiSA==,type:str]
kind: ENC[AES256_GCM,data:RPRiBOly,iv:7YqfrRJeDQuMmnDsY409zB5QC5wf8IA8pFKqB2kK/g0=,tag:wgtytMLJUAthv6057ohHCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zbkiS6DlUsd9pzXR,iv:vq+B70B9o+ixkBruL4TTu/KBMmilWSBlAz44QvtqYOU=,tag:IbSOuxg0WgmCPDkLHs0kfA==,type:str]
    namespace: ENC[AES256_GCM,data:ri6v31ImZxAHBGg=,iv:ppJC9bKDBCaOxM1ROowipVhDe4TwtxUl7jRnEVfdjPs=,tag:ZLi03O5kbMKe7ZKFrXJUXQ==,type:str]
stringData:
    TST_NEXTCLOUD_HOST: ENC[AES256_GCM,data:iLXv6lggLGvL4ze3AOQQHwRfNA==,iv:LJ4Ai6K+A91EXHTFRhi4PJATN0QLf5of26PQppwZqag=,tag:UMKq8FQ7S4xfuaIicKaVvA==,type:str]
    TST_S3_API_HOST: ENC[AES256_GCM,data:mcD/fgMU9nqjgTEHpD+JAo0LOPA=,iv:VqMYwlH8OSaSqyZ15lXTTA5MokBIy7KSCGTufI/Ubog=,tag:qKn0zWINxozsZ9oC3R4o4A==,type:str]
    TST_S3_WEB_HOST: ENC[AES256_GCM,data:azBTmeWT1hneB0WiklNfeMIsuA==,iv:9TOX3MtyJa5QZQlR9fxYamUaGhhe6vFynOrPlqftLjo=,tag:hdGnXdZZj7XGTgc8sieaQQ==,type:str]
    TST_JELLYFIN_HOST: ENC[AES256_GCM,data:vbv+1ONqeU3EA2XlM3Nnww==,iv:8E42DF5iDcv5pcbP/i/H4nrJ4DEJ7g286cuw83JlaAI=,tag:6ABbZbrnPRWZWGOlLbg4oA==,type:str]
    TST_HARBOR_HOST: ENC[AES256_GCM,data:AxXnnYlbUTFN0zp2nKwYyNWIyLM=,iv:eyjcugrb/68kXGvSr31DqAYiM4w7NTeD97o9WJZ+MQY=,tag:DczEBzuwDZowbvHlV6AwKg==,type:str]
    TST_HARBOR_URL: ENC[AES256_GCM,data:0SPx8Rc9lK+fcmwWfAg/Ta5q0sEneq9V67v0Cw==,iv:ytj021mVnDNtMzOwU+G1iKV5vrbjwidfC8zsif4UKyo=,tag:GdZdEYWghRUqNzzW5FFe2w==,type:str]
    TST_PORTAINER_HOST: ENC[AES256_GCM,data:tiN7zM/Q8YGJe2pb9ETZdW3KxLZJOs4=,iv:HsOZXDxNrH+0eRpJ1lrXauEue4ptiSg0zAXkNRa3l1w=,tag:CTRxGCOWejVxJY1Ia16jHQ==,type:str]
    TST_SSO_HOST: ENC[AES256_GCM,data:3qxshgNVYP3MAhbTYDCdcRU=,iv:7hSmvw/9pHOulVpBlels8fbnN/bxl2MfOk3vV2AoQrY=,tag:BK89/4mXP1jve/svfUwVYw==,type:str]
    TST_SSO_URL: ENC[AES256_GCM,data:b/A/UQnYnYP1z5zfpyUeQBdnPps8KPjHOQ==,iv:l5nm0KeKz1EFl1Z74xDtrNb7qOqcakB/zZxbPcVOrvk=,tag:Ss5y5iz+4RsSp4toJKlSew==,type:str]
    TST_JENKINS_HOST: ENC[AES256_GCM,data:7y+c2b5nRAXqeAq7MchHF5IBnZJT,iv:/CxZgoLqC+m2BZh6wpxj7f83q7oeKQOm1e+BhLLxJDQ=,tag:63QRqWNCt3Go2NKzR4/nJQ==,type:str]
    TST_FORGEJO_HOST: ENC[AES256_GCM,data:mD3NG94MznuFiSIwEC+KFiWT,iv:G6PYLnQ5JPRKcynrTVLpHRDxGf8m4UQW5WQQMav8VXc=,tag:IKKqHQqm3uxIqBhDZ2C9qg==,type:str]
    TST_FORGEJO_URL: ENC[AES256_GCM,data:Bb5tRa01VzeZJ0FE+9zrMkknCZoT2SC+Tt4=,iv:p3N+rISctMVn8WcJxmwYYdXmzW+AsNMAHEw88ZdNz70=,tag:VcGXC6ZO3H1ohGGw1OV1iw==,type:str]
    CLOUDFLARE_TUNNEL_TARGET: ENC[AES256_GCM,data:QD+ooEJR8z5luR+Az0MHKRF2u0yKDLykZClKDw==,iv:XcWfDCUrQLips6gXtsdSMjAgBv6uOj5vXk9yY+Hho94=,tag:6+M+RT8Ds6k70YE6HAyMsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZGpISzNhTkdJZDhYTXJY
            dmNCeDJ6MS9JTlFoNitnREplR3U2cjBCd0g0CnJSRXVINFZRUFUyeTlnQ0pyREx2
            NzYxWi95Q0plb1BNai85T0F2bzJzcmcKLS0tIDN4VlZWQlZ4Umh4SnU0M3lmNmpu
            ZS9leElLVW1jZUJZMk9UUjJsUCsremsK6O5sXOINYbgky+uuhg942XP4GlO7/oBL
            Gk530ouLYKT+c7wAQdfKeTNcSN+MGpIx5GXJgHT634UVpyzh70Z1Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwhpwjgw3c7trgrtjv7k309suma9l6qu8yrh4at80clrymrczvss8xq69u
    lastmodified: "2026-08-05T12:05:56Z"
    mac: ENC[AES256_GCM,data:a57q5tRZdTL3tueq0709aUiXc3DdQM+0RbOE+qsIabilud4XoTjUARCsDM6o+ujvHpNi7A1s+KRruFzmiT1XPP8ZOXMywAKr8ZBYK8Tl5X1o9MyImCwpk0n3DZ9khQJ8uwgdmoKRcoBG3AOW3tnDPX6BtlpEXVAy7NwGa4o2So0=,iv:Q0VfI0kS6k7hNLCjBfNdZDSOqqnrJm+IGdwhgTuXSpw=,tag:p+FMBPj9cRT5Z0dj5s2h4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
