---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-admission-controller
spec:
  maxHistory: 20
  chart:
    spec:
      chart: admission-controller
      version: ">=0.6.24"
  values:
    sysdig:
      url: https://eu1.app.sysdig.com
    clusterName: ranchernuc
    scanner:
      enabled: true
