---
apiVersion: v1
kind: ConfigMap
metadata:
  name: net-mon-configmap
  labels:
    app: network-exporter
data:
  network_exporter.yml: |
    conf:
      refresh: 15m
      nameserver: 10.10.8.1:53

      icmp:
        interval: 3s
        timeout: 1s
        count: 6

      mtr:
        interval: 3s
        timeout: 500ms
        max-hops: 30
        count: 6

      cp:
       interval: 3s
       timeout: 1s

      http_get:
        interval: 15m
        timeout: 5s

      targets:
        - name: internal
          host: 10.10.8.1
          type: ICMP
          probe:
            - hostname1
            - hostname2
        - name: google-dns1
          host: 8.8.8.8
          type: ICMP
        - name: google-dns2
          host: 8.8.4.4
          type: MTR
        - name: cloudflare-dns
          host: 1.1.1.1
          type: ICMP+MTR
        - name: cloudflare-dns-https
          host: 1.1.1.1:443
          type: TCP
        - name: opendns-1
          host: 208.67.220.220
          type: ICMP
        - name: fw-bras
          host: 10.2.3.82
          type: ICMP
        #  - name: download-file-64M
        #    host: http://test-debit.free.fr/65536.rnd
        #    type: HTTPGet
        #  - name: download-file-64M-proxy
        #    host: http://test-debit.free.fr/65536.rnd
        #    type: HTTPGet
