---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: network-exporter
  name: network-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9427'
      labels:
        app: network-exporter
    spec:
      containers:
      - image: syepes/network_exporter
        name: network-exporter
        volumeMounts:
          - mountPath: /network_exporter.yml
            name: net-mon-config
        ports:
          - containerPort: 9427
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
    volumes:
      - name: net-mon-config
        configMap:
          name: net-mon-configmap
