apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: betterstack-token
  namespace: flux-system
spec:
  itemPath: "vaults/66qfxcmgwlhutunx6slav6fyve/items/gs7krh67c5dyeofbtvj4ftbhdi"
