---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: awx-backup
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pgbackup
            image: schickling/postgres-backup-s3
            imagePullPolicy: IfNotPresent
            env:
            - name: S3_REGION
              value: "eu-south-1"
            - name: POSTGRES_BACKUP_ALL
              value: false
            - name: POSTGRES_EXTRA_OPTS
              value: "--schema=public --blobs"
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-backup
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-backup
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-backup
                  key: S3_BUCKET
            - name: S3_PREFIX
              value: "awx-backup"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: awx-postgres-configuration
                  key: host
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: awx-postgres-configuration
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: awx-postgres-configuration
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: awx-postgres-configuration
                  key: password
          restartPolicy: OnFailure