---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zabbix-proxy
  namespace: flux-system
spec:
  targetNamespace: zabbix
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/kubenuc/apps/zabbix/manifests
  prune: true
  patches:
    - target:
        kind: HelmRelease
        name: zabbix
      patch: |
        - op: remove
          path: /spec/values/nodeSelector
