name: Test
on:
  workflow_dispatch:

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test setup script
        env:
          OP_TOKEN: '${{ secret.OP_TOKEN }}'
          OP_ENDPOINT: '${{ secret.OP_ENDPOINT }}'
        run: |
          bash terraform/rabbit-01-psp/setup.sh
