#!/usr/bin/env python3
"""Regenerate manifests/error-files.yml (HAProxy --configmap-errorfiles).

HAProxy errorfiles must fit in tune.bufsize (16 KiB), but the upstream
tarampampam/error-pages pages are ~60 KiB because of two inline <script>
blocks (localization + connectivity check). This renders each page from the
pinned upstream image, strips the scripts and comments, and wraps the result
as a complete raw HTTP response (status line, headers, blank line, body).

Usage: ./generate-error-files.py [image-tag]   (needs docker + curl)
Keep the tag in line with the error-pages chart version in
apps/error-pages/manifests/release.yml. Never raise tune.bufsize instead.
"""
import re
import subprocess
import sys
import time

TAG = sys.argv[1] if len(sys.argv) > 1 else "4.2.5"
THEME = "connection"
PORT = "18081"
MAX_BYTES = 15 * 1024  # headroom under the 16 KiB tune.bufsize
CODES = {
    400: "Bad Request",
    403: "Forbidden",
    408: "Request Timeout",
    500: "Internal Server Error",
    502: "Bad Gateway",
    503: "Service Unavailable",
    504: "Gateway Timeout",
}


def sh(*cmd):
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


name = "error-files-gen"
subprocess.run(["docker", "rm", "-f", name], capture_output=True)
sh("docker", "run", "-d", "--rm", "--name", name, "-p", f"{PORT}:8080",
   "-e", f"TEMPLATE_NAME={THEME}", f"ghcr.io/tarampampam/error-pages:{TAG}")
try:
    for _ in range(30):
        if subprocess.run(["curl", "-sf", f"localhost:{PORT}/healthz"],
                          capture_output=True).returncode == 0:
            break
        time.sleep(1)
    out = [
        "---",
        "# GENERATED by ../generate-error-files.py - do not edit by hand.",
        f"# Source: tarampampam/error-pages {TAG}, theme {THEME}, scripts stripped.",
        "# Each value is a complete raw HTTP response; it replaces only",
        "# HAProxy-generated errors, never an error returned by a backend.",
        "apiVersion: v1",
        "kind: ConfigMap",
        "metadata:",
        "  name: error-files",
        "  namespace: haproxy-ingress",
        "data:",
    ]
    for code, phrase in CODES.items():
        html = sh("curl", "-sf", "-H", "Accept: text/html", f"localhost:{PORT}/{code}")
        html = re.sub(r"<script>.*?</script>", "", html, flags=re.S)
        html = re.sub(r"<!--.*?-->", "", html, flags=re.S)
        html = re.sub(r"\n\s+", "\n", html).strip() + "\n"
        assert "$" not in html, "'$' would be touched by Flux postBuild substitution"
        resp = (f"HTTP/1.0 {code} {phrase}\n"
                "Cache-Control: no-cache\n"
                "Connection: close\n"
                "Content-Type: text/html; charset=utf-8\n"
                "\n" + html)
        size = len(resp.encode())
        assert size < MAX_BYTES, f"{code}: {size} bytes exceeds {MAX_BYTES}"
        print(f"{code}: {size} bytes", file=sys.stderr)
        out.append(f'  "{code}": |')
        out.extend(("    " + l) if l else "" for l in resp.rstrip("\n").split("\n"))
    open(__file__.rsplit("/", 1)[0] + "/manifests/error-files.yml", "w").write("\n".join(out) + "\n")
finally:
    subprocess.run(["docker", "rm", "-f", name], capture_output=True)
