---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: sysdig
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: sysdig-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    clusterName: k8s-daniele-vms
    resourceProfile: custom
    resources:
      requests:
        cpu: 300m
        memory: 600Mi
      limits:
        cpu: 500m
        memory: 1Gi
    nodeAnalyzer:
      apiEndpoint: app.sysdigcloud.com
      runtimeScanner:
        deploy: true
        settings:
          eveEnabled: true
    secure:
      vulnerabilityManagement:
        newEngineOnly: true
    sysdig:
      existingAccessKeySecret: sysdig-agent
      settings:
        k8s_extra_resources:
            include:
              - services
              - resourcequotas
              - persistentvolumes
              - persistentvolumeclaims
        log:
          file_priority: info
          console_priority: warning
        metrics_filter:
          - include: "container_fs*"
          - exclude: "container_*"
        prometheus:
          enabled: true
          prom_service_discovery: true
        app_checks_enabled: false
        feature:
         mode: monitor
        skip_events_by_process:
          - fluent-bit
          - kubelet
          - dockerd
        skip_events_by_type:
          - recvfrom
