version: "3.7"

services:
  nut-exporter:
    image: hon95/prometheus-nut-exporter:1
    container_name: nut-exporter
    environment:
      - TZ=Europe/Rome
      - HTTP_PATH=/metrics
      # Defaults
      #- RUST_LOG=info
      #- HTTP_PORT=9995
      #- HTTP_PATH=/nut
      #- LOG_REQUESTS_CONSOLE=false
      #- PRINT_METRICS_AND_EXIT=false
    ports:
      - "9995:9995/tcp"
    restart: always
