---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: intel-gpu-plugin
spec:
  interval: 15m
  maxHistory: 20
  chart:
    spec:
      chart: intel-gpu-plugin
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    env:
      TZ: "Europe/Rome"
    common:
      nodeSelector:
        gputype: "intel"
